version: '2'
services:
  relc:
    build: ./relc
    restart: always
    depends_on:
      - database
    ports:
      - 5000:5000

  relc-frontend-student:
    build: ./relc-frontend-student
    restart: always
    ports:
      - 3001:3001

  relc-frontend-teacher:
    build: ./relc-frontend-teacher
    restart: always
    ports:
      - 3000:3000

  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data/database:/var/lib/mysql