// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relc.Data;

namespace relc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200516111935_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("relc.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("GradingScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("GradingScoreMin")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoundingMethod")
                        .HasColumnType("int");

                    b.Property<short>("ScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeLimitSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("relc.Models.ExamAttempt", b =>
                {
                    b.Property<int>("ExamAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeTaken")
                        .HasColumnType("smallint");

                    b.HasKey("ExamAttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("LoginId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("relc.Models.ExamAttemptAnswer", b =>
                {
                    b.Property<int>("ExamAttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamAttemptId")
                        .HasColumnType("int");

                    b.HasKey("ExamAttemptAnswerId");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("ExamAttemptAnswers");
                });

            modelBuilder.Entity("relc.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AlwaysAppear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ExamQuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("relc.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Mandingo",
                            NameLast = "The Great",
                            Password = "AQAAAAEAACcQAAAAEMB3dHqKD+OSbkkRDi85C9klMy4Q2uAZHGuW12rj8i8kRjNsFreVahofpYFsMlsRFg==",
                            Type = 1,
                            Username = "mandingo"
                        },
                        new
                        {
                            LoginId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Станимир",
                            NameLast = "Стоянов",
                            Password = "AQAAAAEAACcQAAAAELG8kUJRWU1Dow9iWbVaWV8XkGfxd4Ett4WohiShBWdIxMyLVaiXpIGPSGZ/6fH9cg==",
                            Type = 1,
                            Username = "brek"
                        },
                        new
                        {
                            LoginId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Бекирски",
                            Password = "AQAAAAEAACcQAAAAEM/yfymPvzU1FA698CqMKz6dX45JiyS584DRbZbvccyt9ACH8Qee7bKr/v0SXb0iTw==",
                            Type = 2,
                            Username = "1803261001"
                        },
                        new
                        {
                            LoginId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Желязков",
                            Password = "AQAAAAEAACcQAAAAEBqoJ4zUJ3d2xzkWUje8hVhMfUPtZMcEBPhtpx13xT+SEGTmD3mh5+TdUo2ZJADo6A==",
                            Type = 2,
                            Username = "1803261002"
                        },
                        new
                        {
                            LoginId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иоан",
                            NameLast = "Аврамов",
                            Password = "AQAAAAEAACcQAAAAED8Vllwz+FDtVXI7Hvko+9VwW9Es+VOQI9fCKzZQBKvF72mNxV+JSGL6L45ULIhuww==",
                            Type = 2,
                            Username = "1803261003"
                        },
                        new
                        {
                            LoginId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мария",
                            NameLast = "Павлова",
                            Password = "AQAAAAEAACcQAAAAEPimJV3iG49Zs1jg2j/LJY2KMbUNLgMZG6xeYACuwa2+KDo8v+ATSOf7mwtNwUrrFQ==",
                            Type = 2,
                            Username = "1803261004"
                        },
                        new
                        {
                            LoginId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEGmiYZRDm05djC+crlEFsjx5Nw9wduxclnxyTJG7drpHqSNZ/iUIQ9iXdmdXXZ60Dg==",
                            Type = 2,
                            Username = "1803261005"
                        },
                        new
                        {
                            LoginId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невена",
                            NameLast = "Мандева",
                            Password = "AQAAAAEAACcQAAAAEMNR68/+aUptN2MlFDCgGc9preOBVh3swubR8QYS/yi6C9J+ULeoQEouOTqc61cXEg==",
                            Type = 2,
                            Username = "1803261006"
                        },
                        new
                        {
                            LoginId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невелина",
                            NameLast = "Аладжова",
                            Password = "AQAAAAEAACcQAAAAEMwOJFA/tbctEPBKj+4upiIUfKg/gP1iTWyqQSChaYcerwNbSIdgXeeAQGJqqnvVzQ==",
                            Type = 2,
                            Username = "1803261007"
                        },
                        new
                        {
                            LoginId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Стефан",
                            NameLast = "Кючуков",
                            Password = "AQAAAAEAACcQAAAAELaCpPLJTrXfzkg++SXokxuEFQFLINDNxbhtcr7OkvOLNZhEXV05iDbwmr+gwJ/XTw==",
                            Type = 2,
                            Username = "1803261008"
                        },
                        new
                        {
                            LoginId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румен",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEI7+zcwIeTezhu0WNr4NrjJ3nZ8UHbvnbo9yyQhVQJ7T8zaWMxw4emCa5elsCX3jcw==",
                            Type = 2,
                            Username = "1803261009"
                        },
                        new
                        {
                            LoginId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Пачелийска",
                            Password = "AQAAAAEAACcQAAAAEIipOrxmqCnYcejEiCZNJ2w5PHSfhubOtUWt8R4imfagKl923llPv/89G5Et6eTY+w==",
                            Type = 2,
                            Username = "1803261010"
                        },
                        new
                        {
                            LoginId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емилия",
                            NameLast = "Назърова",
                            Password = "AQAAAAEAACcQAAAAEL9Gkj/LDK180ZdXrvU8HIOrnANgaEl8eKKVKUcE7ZzoTMc9kErTX66BEpHWYraT6w==",
                            Type = 2,
                            Username = "1803261011"
                        },
                        new
                        {
                            LoginId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Веселин",
                            NameLast = "Станчев",
                            Password = "AQAAAAEAACcQAAAAEJllhG/QOl13D/j5+MEp7jnHFDpwy6PrKfxlOlJ40/CLxt2AIVCA8ugYAFfnBKbDdg==",
                            Type = 2,
                            Username = "1803261012"
                        },
                        new
                        {
                            LoginId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иван",
                            NameLast = "Иванов",
                            Password = "AQAAAAEAACcQAAAAECNSpcBbimb4mJUMNXcRoJ5bqBlup7h7YBXcOaBAaxMMxxk7408LgZxo1m/tLB49eQ==",
                            Type = 2,
                            Username = "1803261014"
                        },
                        new
                        {
                            LoginId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирил",
                            NameLast = "Караколев",
                            Password = "AQAAAAEAACcQAAAAEHWCua9rOIp+N0GrcDzGgC90y3zcdLSaSJ5WFpsPCGvS0fFE/J6NH0WdtpFux6L+RQ==",
                            Type = 2,
                            Username = "1803261015"
                        },
                        new
                        {
                            LoginId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Маноела",
                            NameLast = "Неделчева",
                            Password = "AQAAAAEAACcQAAAAEK4bpLf2+4zQwtehkskIyr8cCKLbezNLaNHRAnbVb7JOkpdPNyxXXecbUciLjaQ0tQ==",
                            Type = 2,
                            Username = "1803261016"
                        },
                        new
                        {
                            LoginId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Айгюл",
                            NameLast = "Аптурахим",
                            Password = "AQAAAAEAACcQAAAAEKCXhYVT6VkTA0/qWVCZ8t1kJMueOufpigNMe8EyzBRtHhYGJMZdCzhNFSw9/bPb0w==",
                            Type = 2,
                            Username = "1803261017"
                        },
                        new
                        {
                            LoginId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Камен",
                            NameLast = "Трайков",
                            Password = "AQAAAAEAACcQAAAAEP8pSWgO/y5eUpLaT4XrgR0oWFQ0M5/Gy6KkptMcIRipnJp3pGsKk6shdpThbAzyow==",
                            Type = 2,
                            Username = "1803261018"
                        },
                        new
                        {
                            LoginId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румяна",
                            NameLast = "Мурлева",
                            Password = "AQAAAAEAACcQAAAAEEUW3dr3Cbne1kkk2lHFxn37zzos6Rs1TX4WLDP7I5Up0LQn4IfrIsJ2OkjVb40FxA==",
                            Type = 2,
                            Username = "1803261019"
                        },
                        new
                        {
                            LoginId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антоан",
                            NameLast = "Майдозян",
                            Password = "AQAAAAEAACcQAAAAEBxrW6SyHNtWD9finV2QdSK29mwX71mJJm4NdLz+hgUg3PgHzvak9Fus9o5d5+d1mg==",
                            Type = 2,
                            Username = "1803261020"
                        },
                        new
                        {
                            LoginId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велислав",
                            NameLast = "Андонов",
                            Password = "AQAAAAEAACcQAAAAEPclHhDJh0GJ2znGIY0tMr4aZq+znt1Cu2iVP9PgBEcM8xdNVViaVBJT3Pv399ngKA==",
                            Type = 2,
                            Username = "1803261021"
                        },
                        new
                        {
                            LoginId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Данчев",
                            Password = "AQAAAAEAACcQAAAAEObAvU8sMOpWBbQESqpQ7e0Jo1UDS32K+Jxys+9OXA6dorluauQ9WTKhpzl+Qi3qGA==",
                            Type = 2,
                            Username = "1803261022"
                        },
                        new
                        {
                            LoginId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Икимов",
                            Password = "AQAAAAEAACcQAAAAELMuGYggD8vfZLx5KAd0OVI3hX0vDiAIUyLj0n+ktKCrivuK/OaEgbt0BPlK7WzFQA==",
                            Type = 2,
                            Username = "1803261023"
                        },
                        new
                        {
                            LoginId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Василев",
                            Password = "AQAAAAEAACcQAAAAEEdtjp9AovpQNzKkTSSa9FDv4fLliV+Xa2zhiIwC4aFhv5n2awh9xWCdrgwux94nww==",
                            Type = 2,
                            Username = "1803261024"
                        },
                        new
                        {
                            LoginId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ирина",
                            NameLast = "Циркалова",
                            Password = "AQAAAAEAACcQAAAAEKHU/ch9C4gBEwEfOoa1nETkssUvsylDczkEYBbv7m4fxrYBfv44CST4h5BP78Prqw==",
                            Type = 2,
                            Username = "1803261025"
                        },
                        new
                        {
                            LoginId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Сидеров",
                            Password = "AQAAAAEAACcQAAAAEI0clmZCY81oWnvhsmUhmXGm0fzPv05S+IAq3bd8OIokn+66EWSN6MWOUi2Zl4PoqA==",
                            Type = 2,
                            Username = "1803261026"
                        },
                        new
                        {
                            LoginId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Елиан",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAENMWImO+Ztj5rzufaVXaaR64Q7sSZRa+U4I6BR4uUvXsKqBIyNp0e4yNnuINfdRIvg==",
                            Type = 2,
                            Username = "1803261027"
                        },
                        new
                        {
                            LoginId = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Росен",
                            NameLast = "Рунтев",
                            Password = "AQAAAAEAACcQAAAAEHDjrEidlBVRO+397d67ykazHf4ZFvGE8PeSmUCuvShtwC/8f+R3RHMXTrfasC4xmg==",
                            Type = 2,
                            Username = "1803261028"
                        },
                        new
                        {
                            LoginId = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Надежда",
                            NameLast = "Георгиева",
                            Password = "AQAAAAEAACcQAAAAEOvjldcwVYYjlXD5cMk2/nGta8Gik+Oq6Jq8PvCRAl5YFpikfNwsrS3tgyUmNRlPvQ==",
                            Type = 2,
                            Username = "1803261029"
                        },
                        new
                        {
                            LoginId = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Узунов",
                            Password = "AQAAAAEAACcQAAAAEBcQZSr5lquHjbHXBIBSVTuxHoUg73Nitqlesv4PzgOldeqCEW2UYbHkdFs+daK+Kw==",
                            Type = 2,
                            Username = "1803261030"
                        },
                        new
                        {
                            LoginId = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Маламов",
                            Password = "AQAAAAEAACcQAAAAEMC6keVbIDpaDEtv57Eo+1HN8UWC++zx++L+8AaSUgMegmW6I71zSKLIjKyPSX3dXg==",
                            Type = 2,
                            Username = "1803261031"
                        },
                        new
                        {
                            LoginId = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Даниел",
                            NameLast = "Леви",
                            Password = "AQAAAAEAACcQAAAAEHcRK9NC9TAuNMwoX4bE9Ih4rdFewvxS6P2QLhywvUyOLS9vHNDTWSoqNjGGyNZhPw==",
                            Type = 2,
                            Username = "1803261032"
                        },
                        new
                        {
                            LoginId = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сабри",
                            NameLast = "Юмер",
                            Password = "AQAAAAEAACcQAAAAEA85/RfM0XxZVe8aqbLDgvoU3xmBSZCtU5RGewFvl7//Z1hkKZhNvcrbEiKwR5Ah5w==",
                            Type = 2,
                            Username = "1803261033"
                        },
                        new
                        {
                            LoginId = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бедреттин",
                            NameLast = "Бекир",
                            Password = "AQAAAAEAACcQAAAAEDyPK4rh3XLeM+vbv1A23gp+jtZ17A0ozonOStFCJfqQNZPTdtNCTNLWIc26dLGuRg==",
                            Type = 2,
                            Username = "1803261034"
                        },
                        new
                        {
                            LoginId = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Боянов",
                            Password = "AQAAAAEAACcQAAAAEC3Ki6nSx2ARVWorV8Co+/qEEwIHd75VKTDMwXnklg+A8cd+dhawKfs/VC73HofBQQ==",
                            Type = 2,
                            Username = "1803261035"
                        },
                        new
                        {
                            LoginId = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитрия",
                            NameLast = "Христева",
                            Password = "AQAAAAEAACcQAAAAEOM491pdVkwkSmPuk2XpE3vcZOk01w0RenY2X9X+P/BA6CoVMwb7GQfi5xpEjw+mjw==",
                            Type = 2,
                            Username = "1803261036"
                        },
                        new
                        {
                            LoginId = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Момчилова",
                            Password = "AQAAAAEAACcQAAAAEJUHqsZT9C0V955VexB69DOp3lNsbqZ/X6AgRXa07uOUPPa/zs3RrwDh/8PnFj5EUw==",
                            Type = 2,
                            Username = "1803261037"
                        },
                        new
                        {
                            LoginId = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Бютюнев",
                            Password = "AQAAAAEAACcQAAAAEG7YUrK+BQhA7jaAeSy349rtLCiAYflCBTGc6KWmO2MG/mGilvd0pnNRG2K22/9pqw==",
                            Type = 2,
                            Username = "1803261038"
                        },
                        new
                        {
                            LoginId = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Савова",
                            Password = "AQAAAAEAACcQAAAAEE87H0EG59uNJvaZ1am0sNzJFfJmb2ED4XsDOBZ9wQnlNXg/vrQwWOhePJe24tu7og==",
                            Type = 2,
                            Username = "1803261039"
                        },
                        new
                        {
                            LoginId = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Калин",
                            NameLast = "Йержабек",
                            Password = "AQAAAAEAACcQAAAAECaN5UUFmTovoFjGBV74AXGge2dZrpqY373Jq5o9or16bpwwusIlembV8x9rurDomA==",
                            Type = 2,
                            Username = "1803261040"
                        },
                        new
                        {
                            LoginId = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бурджу",
                            NameLast = "Бахри",
                            Password = "AQAAAAEAACcQAAAAEDZ0/BFOKI9NnBpSYN4qdzKvhAvDJ2rDknOSvBQyG+k1VmxDfBMC8uD8ShLzRFmK8A==",
                            Type = 2,
                            Username = "1803261041"
                        },
                        new
                        {
                            LoginId = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емил",
                            NameLast = "Пеев",
                            Password = "AQAAAAEAACcQAAAAEL9YpnOlHLArodYqpUlbufrkrf57pofac7SytmgHAh9209IYTWj4t7qFihkfM4Yp6A==",
                            Type = 2,
                            Username = "1803261042"
                        },
                        new
                        {
                            LoginId = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иванина",
                            NameLast = "Иванова",
                            Password = "AQAAAAEAACcQAAAAEB7uoqoN7W8IrkUhNEPx7gVnc90/ZaIFtvl55eh5ryGpVf8niYRnMJKfn+LrNED9oA==",
                            Type = 2,
                            Username = "1803261043"
                        },
                        new
                        {
                            LoginId = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Диян",
                            NameLast = "Недков",
                            Password = "AQAAAAEAACcQAAAAEPtkLiYU26xSDdeQJy7cfNoD+I1tg3incAWsHPWnfhR3D7wsNriO3n3f5vgOah9XZQ==",
                            Type = 2,
                            Username = "1803261044"
                        },
                        new
                        {
                            LoginId = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Едис",
                            NameLast = "Хаджи",
                            Password = "AQAAAAEAACcQAAAAEII24cKjJjdip1UZiZ/tvf5sQ2BI+KMHMzNS3b/1XoEru5E/S7hHGIGWmWAc6IT1Hw==",
                            Type = 2,
                            Username = "1803261045"
                        },
                        new
                        {
                            LoginId = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йоан",
                            NameLast = "Караманов",
                            Password = "AQAAAAEAACcQAAAAEFeOLKSmcqdvT5S+5088+4jKZox+AK0nr6mRFOBNBFZmDpCD4CHViMghB2iT8biX3w==",
                            Type = 2,
                            Username = "1803261046"
                        },
                        new
                        {
                            LoginId = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велизар",
                            NameLast = "Велев",
                            Password = "AQAAAAEAACcQAAAAECeCzqxTk6wsTzXKlkf+zie1fB4vGca+4+d1MMFluyLKD3biOkkLDe3sTa+gT8abYw==",
                            Type = 2,
                            Username = "1803261047"
                        },
                        new
                        {
                            LoginId = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Джан",
                            NameLast = "Махмуд",
                            Password = "AQAAAAEAACcQAAAAENe7bAb9w7BPhUe/1dMPbWBRCKmbsP6AGosRbORksAKRveH9e12vPtZgCWScKO2ZDA==",
                            Type = 2,
                            Username = "1803261048"
                        },
                        new
                        {
                            LoginId = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Марияна",
                            NameLast = "Бояджиева",
                            Password = "AQAAAAEAACcQAAAAEHf14vOxvH212VZLANkN7ZCVjwA/QKCBhSS0e3rNVgsiNuztNU/gELT2GbNamulwTg==",
                            Type = 2,
                            Username = "1803261049"
                        },
                        new
                        {
                            LoginId = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAENo+DnuC1DWl54J7b0f2tSl3RF9l9Y4GA10Kh55V4K7NZy0W8o5lxH6UYiUjGAsG2g==",
                            Type = 2,
                            Username = "1803261050"
                        },
                        new
                        {
                            LoginId = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Мурджев",
                            Password = "AQAAAAEAACcQAAAAEBUn3pa6q00OcMCoUfFMtIjrgMZIDmt63eOeAhdK8QJNAvm5NKMWbFC1E4bAvErnvg==",
                            Type = 2,
                            Username = "1803261051"
                        },
                        new
                        {
                            LoginId = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Андрий",
                            NameLast = "Ряпов",
                            Password = "AQAAAAEAACcQAAAAEFf9Qiij6MbLap7J59tW27NYZaUy5OX91OLxAH1kVR+WsuMmboC+SmI0LN+qvqfuEw==",
                            Type = 2,
                            Username = "1803261052"
                        },
                        new
                        {
                            LoginId = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Вейсел",
                            NameLast = "Русков",
                            Password = "AQAAAAEAACcQAAAAEDdSw9pVkQIHRCL5CDqE1liKEYUYA9tGTpWedoO4cLjvkkpsSWYPegTYRZrnLwSYGw==",
                            Type = 2,
                            Username = "1803261053"
                        },
                        new
                        {
                            LoginId = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриела",
                            NameLast = "Михайлова",
                            Password = "AQAAAAEAACcQAAAAEPI/TptWM8QPdB3Nh4aOm5vR1m/FQdpsu1ruHisTiC+L/mpc6tv/XSxXHT5/hCaZig==",
                            Type = 2,
                            Username = "1803261054"
                        },
                        new
                        {
                            LoginId = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEPLrceBhsq1pDb0hisLMmX42NTDHctGIs2vjmpoObCVBA+mVmnxCqCUHZC9eMw4AUw==",
                            Type = 2,
                            Username = "1803261055"
                        },
                        new
                        {
                            LoginId = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антони",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEP6E3w89M3sVx92MJ1+C1Dp43sXNbPfL0O5bxUMslnOrqsSopjak5HNqfKFh/pT62Q==",
                            Type = 2,
                            Username = "1803261056"
                        },
                        new
                        {
                            LoginId = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Щилян",
                            NameLast = "Казаков",
                            Password = "AQAAAAEAACcQAAAAEKWLHDuvBlcWxVgYha35uP+YMSCQe+0eXrbWYymND2D4TYjEqJQvv2/xbUjsp303gg==",
                            Type = 2,
                            Username = "1803261057"
                        },
                        new
                        {
                            LoginId = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Парушев",
                            Password = "AQAAAAEAACcQAAAAEJJACpMeT1wAqnp00ZH3cEE4gl5UrLvg1dI7luAY/9UvsMJTg2x836AV41Yrdabmvw==",
                            Type = 2,
                            Username = "1803261058"
                        },
                        new
                        {
                            LoginId = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Кратунова",
                            Password = "AQAAAAEAACcQAAAAEBXLuC/baElCtAtHRKKJcy4024jxfOk/AmzX/BCmWM40ONz4baPJbZ1osTB6aew9sg==",
                            Type = 2,
                            Username = "1803261059"
                        },
                        new
                        {
                            LoginId = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Спасимир",
                            NameLast = "Тричков",
                            Password = "AQAAAAEAACcQAAAAEIGzHJ/+/2gteSfXLBWp3WrslWzf3hwxuUOrEOCQOvEHu/VlpHigNB/QzS8HL4hSbQ==",
                            Type = 2,
                            Username = "1803261060"
                        },
                        new
                        {
                            LoginId = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Цачева",
                            Password = "AQAAAAEAACcQAAAAEFQIoIpFBGgwYjhBj95yhwynKM3C97PNKOaJy8rQQ7BciXBapOEYMqAwcr2fSxiC3g==",
                            Type = 2,
                            Username = "1803261061"
                        },
                        new
                        {
                            LoginId = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Екрем",
                            NameLast = "Дрянов",
                            Password = "AQAAAAEAACcQAAAAEJDTRrpFR4pR7QhlLZJ/yLTDVOxKF7rRy1vOzo/2Xmi/+B2SHosjju9LQNhfPwHDgg==",
                            Type = 2,
                            Username = "1803261062"
                        },
                        new
                        {
                            LoginId = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ричард",
                            NameLast = "Христов",
                            Password = "AQAAAAEAACcQAAAAEGZfJtPmDNhc7QElTMDxYgRL46cGQ58y9gLdjIw1dNlOQiATh2tmysp3EhvYf8TVlQ==",
                            Type = 2,
                            Username = "1803261063"
                        },
                        new
                        {
                            LoginId = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дейвид",
                            NameLast = "Коуди",
                            Password = "AQAAAAEAACcQAAAAEHwPbEBBLWem71H22JwP2d33aBxBk4S8tckZg2PYo7lAUBArG1nfLEzVUfNjBFlwMA==",
                            Type = 2,
                            Username = "1803261064"
                        },
                        new
                        {
                            LoginId = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дарен",
                            NameLast = "Стоев",
                            Password = "AQAAAAEAACcQAAAAEG1suWVjbtV9+zf1MHbhf37PHKnOmIoyJvufrd+d1pRLh5UJJcKN1Yl327P5xMAGXA==",
                            Type = 2,
                            Username = "1803261065"
                        },
                        new
                        {
                            LoginId = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йосиф",
                            NameLast = "Йозов",
                            Password = "AQAAAAEAACcQAAAAECgrw2iQIbERiyzRnaH6A1vEB6uYaZBjXkeyIjE43UtMIa0/OMFsezYioOKS2bPxkQ==",
                            Type = 2,
                            Username = "1803261066"
                        },
                        new
                        {
                            LoginId = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Кондаков",
                            Password = "AQAAAAEAACcQAAAAEOTVtVyRPAY03b43qy95kX/Kv4uzjl4HmL3IHxDZRpgcCxSuPOKrHzTpNKuXAgBblA==",
                            Type = 2,
                            Username = "1803261067"
                        },
                        new
                        {
                            LoginId = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бианка",
                            NameLast = "Минева",
                            Password = "AQAAAAEAACcQAAAAELTKd87nUSXAUMyunJCD0ng9Y3yY++VANbPLnghqRmmkvSvd+xuYA5j5m7fVwWrYKw==",
                            Type = 2,
                            Username = "1803261068"
                        },
                        new
                        {
                            LoginId = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEEM3mmEdlWh2jaCGygqGqYV3AdmPlkla7iqI7ey0CFO5x9s0wE5fA33LL/I6OjQQSg==",
                            Type = 2,
                            Username = "1803261069"
                        },
                        new
                        {
                            LoginId = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEApdKgWDaKmOoWGJjJVSnRqTuYIszmOmePjBhCOS+6XsA+Zv5yt03JqaExTrsVtSWg==",
                            Type = 2,
                            Username = "1803261070"
                        },
                        new
                        {
                            LoginId = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Пейчев",
                            Password = "AQAAAAEAACcQAAAAEK8kDXKUzvKEtGLeD5JUD1/YlSsCLdMqh6mFR2boXGsswmz5nzE9FMuvSvTjA6omPA==",
                            Type = 2,
                            Username = "1803261071"
                        },
                        new
                        {
                            LoginId = 73,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEP9/5nwHLwGR2QyPFEg3VpTekzFi+Sj/3fm3QXxUVW9kiGewhxoRyhCBvmFK4TfV6w==",
                            Type = 2,
                            Username = "1803261072"
                        },
                        new
                        {
                            LoginId = 74,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Янев",
                            Password = "AQAAAAEAACcQAAAAEOmrCZa2W7MFHxRtDiP0gm51sv3J3N1il9XmYWpLiDzIo3/5ky7x1Fp2aav/Fw9gZA==",
                            Type = 2,
                            Username = "1803261073"
                        },
                        new
                        {
                            LoginId = 75,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Радостин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEGNd174SNcCydVmfB0hwxBcT0fwuLncsWHN12FKKkHzhVdqT9TMg9YVhufF0n177WQ==",
                            Type = 2,
                            Username = "1803261074"
                        },
                        new
                        {
                            LoginId = 76,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Младенова",
                            Password = "AQAAAAEAACcQAAAAEHGswf91Hpp76FV5DE8fdtJDWU4HRYt+3aUd6zVdDXNE+KD/056MCJaos8oUlWV7ew==",
                            Type = 2,
                            Username = "1803261075"
                        },
                        new
                        {
                            LoginId = 77,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Величка",
                            NameLast = "Стоянова",
                            Password = "AQAAAAEAACcQAAAAEMtq/Gl+/XZ/w1pmQSEjxBf2MS/Gr4PwZmsp2j/Y1uzhgo0FM7jyV35CcleGL30g6w==",
                            Type = 2,
                            Username = "1803261076"
                        },
                        new
                        {
                            LoginId = 78,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Лъчезар",
                            NameLast = "Митев",
                            Password = "AQAAAAEAACcQAAAAEG6/OeSBxNHSmOc+PjvcIhan859cg0a1DsAJDGFwcdEq6D2ISZPLT/ufURwhcaIGFg==",
                            Type = 2,
                            Username = "1803261077"
                        },
                        new
                        {
                            LoginId = 79,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Ангелова",
                            Password = "AQAAAAEAACcQAAAAEF06ZiQ5WLye1cEuipOkjH4dYruLtALimRHfOJzbyu/O6lTgGIEKs8AWIatd2NQ7vw==",
                            Type = 2,
                            Username = "1803261078"
                        },
                        new
                        {
                            LoginId = 80,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Хари",
                            NameLast = "Балабанов",
                            Password = "AQAAAAEAACcQAAAAEIhUpVP+nE2tCUPdCaDhO74ha+fUhWPVorbwmGleZZuYcL+uX9iA45UFZ2MVhqEXCQ==",
                            Type = 2,
                            Username = "1803261079"
                        },
                        new
                        {
                            LoginId = 81,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Незиха",
                            NameLast = "Хаджиева",
                            Password = "AQAAAAEAACcQAAAAEKuHHZoXOe4MxbxV4AkRx4J1UFJeDVfqQgyZOFrQYRiKsjSSQQRotCKzm9dlhaVCTQ==",
                            Type = 2,
                            Username = "1803261080"
                        },
                        new
                        {
                            LoginId = 82,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Недялков",
                            Password = "AQAAAAEAACcQAAAAEJ0MGxZv2ifpRDeteORz2qasvK1O10yXsla6ix4ggqsT8nCngdPlOsIwT9TA0XjDig==",
                            Type = 2,
                            Username = "1803261081"
                        },
                        new
                        {
                            LoginId = 83,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Костадин",
                            NameLast = "Запрянов",
                            Password = "AQAAAAEAACcQAAAAEMgN0NFIaFDCeFw/cL5pMetfhiAhpKBMf3kfXJIGARxj0Vf2WrxjOZKBaTNVL3PbsQ==",
                            Type = 2,
                            Username = "1803261082"
                        },
                        new
                        {
                            LoginId = 84,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриел",
                            NameLast = "Гигов",
                            Password = "AQAAAAEAACcQAAAAEA4uKwImkXht7fer0IyZUl0f+JMb3mF05WATA1Z62hzSZUHjf6Q9p2F9OdYrOvHdCQ==",
                            Type = 2,
                            Username = "1803261083"
                        },
                        new
                        {
                            LoginId = 85,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEI5uMAts9R/ZpvUh1jkmEQSQ/Fsae++VzbtoyKE5iNyNISjkVOTx4yVFwDcDjzqMIQ==",
                            Type = 2,
                            Username = "1803261084"
                        },
                        new
                        {
                            LoginId = 86,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Илиев",
                            Password = "AQAAAAEAACcQAAAAEFJdzSO+5xb53GzZr0i9vQmyUp/nggmB69KJxMeard2ep3T9Eoi01pBkhGphRwpYsw==",
                            Type = 2,
                            Username = "1803261086"
                        },
                        new
                        {
                            LoginId = 87,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кристиян",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEGa0anB4NDUG++czHXC2fpiAoqqbeDzSrYH5usAER90fFp/tD0DtAYlJnfzhCLiRJQ==",
                            Type = 2,
                            Username = "1803261087"
                        },
                        new
                        {
                            LoginId = 88,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Кръстев",
                            Password = "AQAAAAEAACcQAAAAEGJr5uGgzLq70SklMzH+KnK4OjzWaRYLd7x/P5o68Y+CFuLbaz3fk4pNBEWs39E5zQ==",
                            Type = 2,
                            Username = "1803261088"
                        },
                        new
                        {
                            LoginId = 89,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEEzhZmVRhP/MwR6LTq3mgOlJgJ8fxA0kUfG0QNNKJE9LLwhIlMfNEFZGCtSHzO1ZHQ==",
                            Type = 2,
                            Username = "1803261089"
                        },
                        new
                        {
                            LoginId = 90,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Виктор",
                            NameLast = "Хаджиев",
                            Password = "AQAAAAEAACcQAAAAEG9LOuR8ZjKn6vEwXrhG21jPn2cWrW/c144Eu9rMgpqdKd60oViIIoXW32EkNWsyRQ==",
                            Type = 2,
                            Username = "1803261090"
                        },
                        new
                        {
                            LoginId = 91,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дилян",
                            NameLast = "Янков",
                            Password = "AQAAAAEAACcQAAAAEKeE7+BH5RFc4Hi71SYRjkBOJIJPX6bNlhf4Vz7BLJBLBG1jTkTmF3g3ZqI4kN3v4A==",
                            Type = 2,
                            Username = "1803261091"
                        },
                        new
                        {
                            LoginId = 92,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Алекс",
                            NameLast = "Манолов",
                            Password = "AQAAAAEAACcQAAAAED2ycpju+hkEvLMDD2UFzDmrjbproPivImrWlLhGOUSDb+7ISWdJFcgi7KiW40JiIA==",
                            Type = 2,
                            Username = "1803261092"
                        },
                        new
                        {
                            LoginId = 93,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ивелин",
                            NameLast = "Танев",
                            Password = "AQAAAAEAACcQAAAAEHD0idmLSNVpdBVyGG0i4b1CUKtYNHDl7E4z/qkGuaf2/LzFq05dFncadJccxNnplw==",
                            Type = 2,
                            Username = "1803261093"
                        },
                        new
                        {
                            LoginId = 94,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валерий",
                            NameLast = "Шулика",
                            Password = "AQAAAAEAACcQAAAAEO13k8ik1gueaWI9yg+zoDpAm0FtI7k0nCseDLse9vUJhJm8UBXkn4FgJjtoWmAekg==",
                            Type = 2,
                            Username = "1803261094"
                        },
                        new
                        {
                            LoginId = 95,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEFdYTlhEV9sn+Rzq6QKTKXXE1bTvLxd3jle4iz7Zcj0b2KNRMfk5EOyG9Y3sWWeYtA==",
                            Type = 2,
                            Username = "1803261095"
                        },
                        new
                        {
                            LoginId = 96,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валентин",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAENRmoKunr7JiALVh+bZHOf92FxprBd8DID7B5WEREe23J+MPO1Xzor6kkcE4XocaaQ==",
                            Type = 2,
                            Username = "1803261096"
                        },
                        new
                        {
                            LoginId = 97,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Костов",
                            Password = "AQAAAAEAACcQAAAAELvyzVj+6OtOdmAUVBoEyvRLSQ4W8KJy8fg9mnU7StpQc13xLdDQ6EOieukI1s6Ulw==",
                            Type = 2,
                            Username = "1803261097"
                        },
                        new
                        {
                            LoginId = 98,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Владислав",
                            NameLast = "Владов",
                            Password = "AQAAAAEAACcQAAAAEMP3t32zuG3i9tC4N6txoVrStABpTHu0TATknUGKDl8OSnXMteB7R+GkHgI96rSQAA==",
                            Type = 2,
                            Username = "1803261098"
                        },
                        new
                        {
                            LoginId = 99,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEMmJ82Z37BEBUBWU5n6F4Siiyz3UsNN9/erHTwfZVwH3KmpQ4QT1EIQpugsRmfF6Cw==",
                            Type = 2,
                            Username = "1803261099"
                        },
                        new
                        {
                            LoginId = 100,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Артем",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEICWdm/rB88VzIDBj2KtD22XLIsn+aNz3KrEf58wdoNTGBLiNAqcbckiehWANbO8fg==",
                            Type = 2,
                            Username = "1803261100"
                        },
                        new
                        {
                            LoginId = 101,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дмитро",
                            NameLast = "Добрев",
                            Password = "AQAAAAEAACcQAAAAEOWie/cMFYNlwhU2rNm5ZGgXvXp7zudAoKHNaWy1let9dn96ONtUh4s6UShq+hgA/Q==",
                            Type = 2,
                            Username = "1803261101"
                        },
                        new
                        {
                            LoginId = 102,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирило",
                            NameLast = "Безниско",
                            Password = "AQAAAAEAACcQAAAAEJc7Ebq4k29kBXXezZYsaoFwaTczyQ73hcH/YpvngQfUKY3d18CPL5ZRIFNFXiXkQQ==",
                            Type = 2,
                            Username = "1803261102"
                        },
                        new
                        {
                            LoginId = 103,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Биков",
                            Password = "AQAAAAEAACcQAAAAEA/Q0cfaV6FbKeqEl6fx8w40m6oXzD9Lzollgsih+nLANXDplO/CEHGay1y+FckoSQ==",
                            Type = 2,
                            Username = "1803261104"
                        },
                        new
                        {
                            LoginId = 104,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илля",
                            NameLast = "Кирилив",
                            Password = "AQAAAAEAACcQAAAAEOybqIMYGLWxtIEiCQJSJINkz0dRXH8wak6Nu/cDUUN9Udy1adEnhzQHDoR008D+TQ==",
                            Type = 2,
                            Username = "1803261105"
                        },
                        new
                        {
                            LoginId = 105,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Сакали",
                            Password = "AQAAAAEAACcQAAAAEImZKn4XHjfLJ/8HF2izx6qSJpVC/OcB7FLwv9fwzHnM2CgmsYnoTU0VeZVHoGkRLQ==",
                            Type = 2,
                            Username = "1803261106"
                        },
                        new
                        {
                            LoginId = 106,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Денис",
                            NameLast = "Репев",
                            Password = "AQAAAAEAACcQAAAAEIk2KJVvEuXuK5Y4nSS0pIWMjdwuouKV8RcdaEdPolJh46OG6Xr9NVIaraEFBpjhKg==",
                            Type = 2,
                            Username = "1803261108"
                        },
                        new
                        {
                            LoginId = 107,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Вълчанов",
                            Password = "AQAAAAEAACcQAAAAEPFEtx07dZ+PnuQbpmUrZvOW7Vy7xR2NCncSaOLHGwZ8cckOOaaIjrLxMMK1OJXEaA==",
                            Type = 1,
                            Username = "nikiv"
                        });
                });

            modelBuilder.Entity("relc.Models.ExamAttempt", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Login", "Login")
                        .WithMany("ExamsAttempts")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.ExamAttemptAnswer", b =>
                {
                    b.HasOne("relc.Models.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.ExamQuestion", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
