// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relc.Data;

namespace relc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200517101121_Initial4")]
    partial class Initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("GradeRounded")
                        .HasColumnType("smallint");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeTaken")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("LoginId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptAnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("relc.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("GradingScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("GradingScoreMin")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoundingMethod")
                        .HasColumnType("int");

                    b.Property<short>("ScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeLimitSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("relc.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Mandingo",
                            NameLast = "The Great",
                            Password = "AQAAAAEAACcQAAAAECCPxywK13m1pKO0qPK6w99pwsf7GsVshdPLk4HlF9c6W3avRCXlyaoouxzOAncpcQ==",
                            Type = 1,
                            Username = "mandingo"
                        },
                        new
                        {
                            LoginId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Станимир",
                            NameLast = "Стоянов",
                            Password = "AQAAAAEAACcQAAAAEPgzx4x999hnwhOSCFiuxPYuHK0NUox8nJNv45TiNhtOOdquWwtLw+M8pdhoRVuqRg==",
                            Type = 1,
                            Username = "brek"
                        },
                        new
                        {
                            LoginId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Бекирски",
                            Password = "AQAAAAEAACcQAAAAEPQTAClCp6XnJF7KZSPqDIHTVApgv57A5SLp2I6athi7nWnvFwLNOvyNojlPrj7vrA==",
                            Type = 2,
                            Username = "180321001"
                        },
                        new
                        {
                            LoginId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Желязков",
                            Password = "AQAAAAEAACcQAAAAEHdLNTnP38kll3XYuPgWG2abvX+o1MHvNirt9H7eE+1xPZyhpBhXF+dj7INxZp4Dug==",
                            Type = 2,
                            Username = "180321002"
                        },
                        new
                        {
                            LoginId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иоан",
                            NameLast = "Аврамов",
                            Password = "AQAAAAEAACcQAAAAEJHC7vd+Dr4szUQ9PuQrTjedmiczwWx4KMrNOkOZkSy/kgwdwxz7Lcry9JJYJCPOxg==",
                            Type = 2,
                            Username = "180321003"
                        },
                        new
                        {
                            LoginId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мария",
                            NameLast = "Павлова",
                            Password = "AQAAAAEAACcQAAAAEPswy7Yq2o3YPs1bBanZccFqwMvLfRmhOIRO2Z3WRgp5nZN5hVDxPV1hMhy4yuYtNw==",
                            Type = 2,
                            Username = "180321004"
                        },
                        new
                        {
                            LoginId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEEGbuZK57qF/JbH6AoLCENRtex3DgJ6DMoQiXeEnKm3rNDOaX5vKqnTM4MpL6sRz0A==",
                            Type = 2,
                            Username = "180321005"
                        },
                        new
                        {
                            LoginId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невена",
                            NameLast = "Мандева",
                            Password = "AQAAAAEAACcQAAAAEIpr6eJ5MuEt4ICIOwNzJcTTi+cEIjxvorFJUaC8TyAB5SyKRKXMDZcbvuUfEn/kgA==",
                            Type = 2,
                            Username = "180321006"
                        },
                        new
                        {
                            LoginId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невелина",
                            NameLast = "Аладжова",
                            Password = "AQAAAAEAACcQAAAAEG+g8GLfHVNE9ZpYGSyolORRvdv0cYjyljp+lbvFs6BClKfrwcN3BxZeD3oiulSZ8A==",
                            Type = 2,
                            Username = "180321007"
                        },
                        new
                        {
                            LoginId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Стефан",
                            NameLast = "Кючуков",
                            Password = "AQAAAAEAACcQAAAAEHc0vZeeUo4wloz3GlWYLQvsERCKAsXTBEpv7A3vQ58eXR324P92p4URii5mA6a6cA==",
                            Type = 2,
                            Username = "180321008"
                        },
                        new
                        {
                            LoginId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румен",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEBLGSyz7XT1n4m8A9Ije6CBGddglVI+g4/IzxCUGeA99rxseRVWL6v2w3qLdgCve0Q==",
                            Type = 2,
                            Username = "180321009"
                        },
                        new
                        {
                            LoginId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Пачелийска",
                            Password = "AQAAAAEAACcQAAAAELUeyc1l1C3yocHBC6Qr7xcuySY0OAYIpPotfXKKQ44fm67y0nd0xKTsFGn0qLLv9Q==",
                            Type = 2,
                            Username = "180321010"
                        },
                        new
                        {
                            LoginId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емилия",
                            NameLast = "Назърова",
                            Password = "AQAAAAEAACcQAAAAEPwV8T4LS2O5gaDc4pjAp1GuiSsL48zxRycqSjpSgsgOhM8TmRFSymSxYg74/lineg==",
                            Type = 2,
                            Username = "180321011"
                        },
                        new
                        {
                            LoginId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Веселин",
                            NameLast = "Станчев",
                            Password = "AQAAAAEAACcQAAAAEFabfwUbAjyCkUFT1iYZ9UWdpL3gb3R0ktyrMgrFrgKvF2DKHM9ISwnoaA8xkTbaFw==",
                            Type = 2,
                            Username = "180321012"
                        },
                        new
                        {
                            LoginId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иван",
                            NameLast = "Иванов",
                            Password = "AQAAAAEAACcQAAAAEKL2LnjWJvMURRxCmPFCxrhZcRo20XBGph0FID0FSHztwYWgiLdyhIivxbM3oftZ+g==",
                            Type = 2,
                            Username = "180321014"
                        },
                        new
                        {
                            LoginId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирил",
                            NameLast = "Караколев",
                            Password = "AQAAAAEAACcQAAAAEEutCuFGcFT5w+tEuo3Pietd8QNJ/oZ8Y5IOW75KhLfe0Ud8R1CXo060OB4KRpZvhQ==",
                            Type = 2,
                            Username = "180321015"
                        },
                        new
                        {
                            LoginId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Маноела",
                            NameLast = "Неделчева",
                            Password = "AQAAAAEAACcQAAAAENoBKEfXNjTtdYXR0Fhf1Nb32VmCjkM1yxvBtzI4gedRXItLBPD+bK8nLi4oeUe2SQ==",
                            Type = 2,
                            Username = "180321016"
                        },
                        new
                        {
                            LoginId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Айгюл",
                            NameLast = "Аптурахим",
                            Password = "AQAAAAEAACcQAAAAEDC8+g6yrGnlsPmrZCowIw5Sq/miem5GgNsbDAiTNIFwt1nwxg/DcSTxldXcHwxq/Q==",
                            Type = 2,
                            Username = "180321017"
                        },
                        new
                        {
                            LoginId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Камен",
                            NameLast = "Трайков",
                            Password = "AQAAAAEAACcQAAAAELk2P8faaQ7TcJsIUSi3xXmTm5lyQycuxIL33Ns0Q2plouGcuGuRxtnQGq7CAeArww==",
                            Type = 2,
                            Username = "180321018"
                        },
                        new
                        {
                            LoginId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румяна",
                            NameLast = "Мурлева",
                            Password = "AQAAAAEAACcQAAAAECaMULvDFkqZAlW0bb4bi/vayzwTaxTjY31EPuktjql7tcN6WpX2bfjdeEI2jNQYew==",
                            Type = 2,
                            Username = "180321019"
                        },
                        new
                        {
                            LoginId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антоан",
                            NameLast = "Майдозян",
                            Password = "AQAAAAEAACcQAAAAEG7s5ugBtCUpL/pqnT351DP1zPBNxHs78uaQGva11vthiiVlYd+7QpAfkgMwNmHxwg==",
                            Type = 2,
                            Username = "180321020"
                        },
                        new
                        {
                            LoginId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велислав",
                            NameLast = "Андонов",
                            Password = "AQAAAAEAACcQAAAAEE9o0oUp4+h1ZOI7ljw61tx/D3L3IQZ+n85YEYTZo/4a/4vwoHtz06EzQ8vvocbGpw==",
                            Type = 2,
                            Username = "180321021"
                        },
                        new
                        {
                            LoginId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Данчев",
                            Password = "AQAAAAEAACcQAAAAEO27kXBqVE1E5q9bnCBTBBYsapzIsdI/VOmtpJ/FjpEWi6BJ5GpzHHFJI9H3RbbB5g==",
                            Type = 2,
                            Username = "180321022"
                        },
                        new
                        {
                            LoginId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Икимов",
                            Password = "AQAAAAEAACcQAAAAEGBoA12rZ2E230fQIffeX3Jy/pzacxqXeIGjkX2gbN9pU/N+LggCiZQd2thKGlrFOA==",
                            Type = 2,
                            Username = "180321023"
                        },
                        new
                        {
                            LoginId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Василев",
                            Password = "AQAAAAEAACcQAAAAEPqjGvuY9dg+uLE2SBtziyEoMD/uP8woF115Dj6oV0oJh21nIbK/MIlPRcMn5xAKzg==",
                            Type = 2,
                            Username = "180321024"
                        },
                        new
                        {
                            LoginId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ирина",
                            NameLast = "Циркалова",
                            Password = "AQAAAAEAACcQAAAAEF0YkTU9Rbr7lowX/Cn5yLTjn4QLiLTJN5xGKVhAoN8c2ry5R2GGJTzVqLDwD/m6qw==",
                            Type = 2,
                            Username = "180321025"
                        },
                        new
                        {
                            LoginId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Сидеров",
                            Password = "AQAAAAEAACcQAAAAEGrWaknLwE0EN4hX1pxbXEhV2/c65xdjV4wxUthL5Ta1C816IeowY27yfZbA1bF+lA==",
                            Type = 2,
                            Username = "180321026"
                        },
                        new
                        {
                            LoginId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Елиан",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEP1QjhtelaWBx//yJOZ1rjiXpIn7iMj3WgBzC4XHcQeDydvtecWbJMEhK9TgNY4wPQ==",
                            Type = 2,
                            Username = "180321027"
                        },
                        new
                        {
                            LoginId = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Росен",
                            NameLast = "Рунтев",
                            Password = "AQAAAAEAACcQAAAAEMxr3s8RMn1ZlQKUlyVKLZCu4slsUDb8sQysL6prheCQlXDD79lpPS6gfd5o+0K5gQ==",
                            Type = 2,
                            Username = "180321028"
                        },
                        new
                        {
                            LoginId = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Надежда",
                            NameLast = "Георгиева",
                            Password = "AQAAAAEAACcQAAAAEOiCss7JikfNmMLjDsDreSbgLbBw8Y4LQphi8coG4Iytg2R4WwBV4LNgQORpwHtwKw==",
                            Type = 2,
                            Username = "180321029"
                        },
                        new
                        {
                            LoginId = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Узунов",
                            Password = "AQAAAAEAACcQAAAAEIrz/w9D/xtFZSrFoOYaqotEymWEMG18yFppIuN3oEyTsdAs4jssd6hMtEJ1glbmTQ==",
                            Type = 2,
                            Username = "180321030"
                        },
                        new
                        {
                            LoginId = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Маламов",
                            Password = "AQAAAAEAACcQAAAAELQw2YAzKYXJ0Cf3dR+S4z3iibtjyx8kaL0FTpOhamh1DIvZ20G+Z7bTjaGQkpl+vQ==",
                            Type = 2,
                            Username = "180321031"
                        },
                        new
                        {
                            LoginId = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Даниел",
                            NameLast = "Леви",
                            Password = "AQAAAAEAACcQAAAAEEDwGSuFiXuwZi7wJ6JADJfTs3atL641T86yyCpRQ2hXCCCdBDpaaxCA+WpAWhRHQA==",
                            Type = 2,
                            Username = "180321032"
                        },
                        new
                        {
                            LoginId = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сабри",
                            NameLast = "Юмер",
                            Password = "AQAAAAEAACcQAAAAEH/7ALGFTSBT+eF0ozvzzKUY/WanRwndk7ujDxCaYiT02MMftolDfcc5vE2VMau8wA==",
                            Type = 2,
                            Username = "180321033"
                        },
                        new
                        {
                            LoginId = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бедреттин",
                            NameLast = "Бекир",
                            Password = "AQAAAAEAACcQAAAAEIm9MHqaEStYp0T0EgZhwHMy+/o+/zvUIVdtnFDUEip/F7U8ENn1zB9vAqX8QzQQNg==",
                            Type = 2,
                            Username = "180321034"
                        },
                        new
                        {
                            LoginId = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Боянов",
                            Password = "AQAAAAEAACcQAAAAEDRla0gbWQi1SwNmE/wO0Q1eb6Uuhg5bM7/IUA2ykBVcDgFF0Gjnj/di1F50BDiGwA==",
                            Type = 2,
                            Username = "180321035"
                        },
                        new
                        {
                            LoginId = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитрия",
                            NameLast = "Христева",
                            Password = "AQAAAAEAACcQAAAAEONT0tzFzyVXY1mz3ipiSVoYzS6Kzu8KgEwiddwf+jZkgRty0/agEkluAaA2s6/nxQ==",
                            Type = 2,
                            Username = "180321036"
                        },
                        new
                        {
                            LoginId = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Момчилова",
                            Password = "AQAAAAEAACcQAAAAEMM9M5y9hHpTyy4aLlx50XHIF2BrcZLdWm5XpFDCNuQ5mGOyTCjOogeWFq2yEuKl2Q==",
                            Type = 2,
                            Username = "180321037"
                        },
                        new
                        {
                            LoginId = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Бютюнев",
                            Password = "AQAAAAEAACcQAAAAEMmqCorHqT9PymJG4SyPgdywJSuL8zun6Ia8zOic8jDKyIzdbjblVT23BuyFSUO9xA==",
                            Type = 2,
                            Username = "180321038"
                        },
                        new
                        {
                            LoginId = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Савова",
                            Password = "AQAAAAEAACcQAAAAEL5+nY8TrpUt323oPAvmdPxgs+X8nlY3UfnzMlbwfyBDo2CU64kSVxvDTGa0FBESXg==",
                            Type = 2,
                            Username = "180321039"
                        },
                        new
                        {
                            LoginId = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Калин",
                            NameLast = "Йержабек",
                            Password = "AQAAAAEAACcQAAAAEMoDVlTJg7f+ZdmBC4B7Uujz7lAmxS49bD0NPYoDeXY2jScecq5etZI5+jaKKKt++Q==",
                            Type = 2,
                            Username = "180321040"
                        },
                        new
                        {
                            LoginId = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бурджу",
                            NameLast = "Бахри",
                            Password = "AQAAAAEAACcQAAAAEGExnzbfOdZjniSB8IIEDZMCe6+ZJNq3a6BLjpvTr94EmZUqmyvRC1JeMT/Z9jQ/vQ==",
                            Type = 2,
                            Username = "180321041"
                        },
                        new
                        {
                            LoginId = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емил",
                            NameLast = "Пеев",
                            Password = "AQAAAAEAACcQAAAAEHLjgQY9mTGGb8B3+Ph7Kp6woP3MEGkA2OcnmURNoKW95ZGmienq7TPiOKyIGsPt4g==",
                            Type = 2,
                            Username = "180321042"
                        },
                        new
                        {
                            LoginId = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иванина",
                            NameLast = "Иванова",
                            Password = "AQAAAAEAACcQAAAAEGzOA+wR4OeloZWc37iXrLtJy8v4V2g+31D/E7yagIJqRE3cFx93bFhPCX34KCUhSg==",
                            Type = 2,
                            Username = "180321043"
                        },
                        new
                        {
                            LoginId = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Диян",
                            NameLast = "Недков",
                            Password = "AQAAAAEAACcQAAAAEKVJumPFEwJqms31onvKb2ktox1F/jbfLeBd6+jNyeUAQ05BBBcxEI8/wwa63HGnBw==",
                            Type = 2,
                            Username = "180321044"
                        },
                        new
                        {
                            LoginId = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Едис",
                            NameLast = "Хаджи",
                            Password = "AQAAAAEAACcQAAAAEBinVGOLik2tPZFyqv55LVk0BKGTVJggCeK9Qgfaj7CTu0yMBVaXOxIKYZjEHZhp8Q==",
                            Type = 2,
                            Username = "180321045"
                        },
                        new
                        {
                            LoginId = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йоан",
                            NameLast = "Караманов",
                            Password = "AQAAAAEAACcQAAAAEET7/h5xEpM1YGoYq9WQdAFaBwzlSmjJEe+J2gaAhXVlq9JlC8V2aILGxl5MX1UAbw==",
                            Type = 2,
                            Username = "180321046"
                        },
                        new
                        {
                            LoginId = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велизар",
                            NameLast = "Велев",
                            Password = "AQAAAAEAACcQAAAAEPmtvT3aw5NYrsN7905osi//GhKO8cClb/Dtq8UMePAvPPKM0n8ZfoZYQxGi1pOTkw==",
                            Type = 2,
                            Username = "180321047"
                        },
                        new
                        {
                            LoginId = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Джан",
                            NameLast = "Махмуд",
                            Password = "AQAAAAEAACcQAAAAEK/Y8NBVQqZY3X7Hyfp3olW32ZPdl1yaWwtJzNAgP+ZYxtCVaTc49a8zHc3Cglweyg==",
                            Type = 2,
                            Username = "180321048"
                        },
                        new
                        {
                            LoginId = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Марияна",
                            NameLast = "Бояджиева",
                            Password = "AQAAAAEAACcQAAAAEOpnfxlaaLzKo3vrXtgP0mNS6odXCBtEeISA9Ul0iHghSQZCsLpLhw1e5NTRSeEw8g==",
                            Type = 2,
                            Username = "180321049"
                        },
                        new
                        {
                            LoginId = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEBdz0Q9DSkXKnfehFIUm/oBuYL1Nf9AjymcDfFfGADmIrQ2qGsOEHoTRBFbCPDcWnA==",
                            Type = 2,
                            Username = "180321050"
                        },
                        new
                        {
                            LoginId = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Мурджев",
                            Password = "AQAAAAEAACcQAAAAEAIm3kiXGinX0QOkNopx1hW9pk8T8QtUUrGW9EJTbfpfq/Tyjl5tjbCLqLIMWRuTaw==",
                            Type = 2,
                            Username = "180321051"
                        },
                        new
                        {
                            LoginId = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Андрий",
                            NameLast = "Ряпов",
                            Password = "AQAAAAEAACcQAAAAEMsL0Rjo1uS8NrAl+aTPSP9Fbq3GKSrWYl5pYfMWrUHlmcqcOba97PMC9cAoucjlPg==",
                            Type = 2,
                            Username = "180321052"
                        },
                        new
                        {
                            LoginId = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Вейсел",
                            NameLast = "Русков",
                            Password = "AQAAAAEAACcQAAAAEBz2AMu5T9osalsL2mORdCOl1YLBKdPG3eXYpau+xD/HJth/+AephH3Ls6uXubgnWg==",
                            Type = 2,
                            Username = "180321053"
                        },
                        new
                        {
                            LoginId = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриела",
                            NameLast = "Михайлова",
                            Password = "AQAAAAEAACcQAAAAELOU3GRPcT+mivK1VntQHV5FNoKCklkN0cfI8mYtzsohI4J2omnp7p1YLXSOzdZJBA==",
                            Type = 2,
                            Username = "180321054"
                        },
                        new
                        {
                            LoginId = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEHxAiTgwfPIxCM1DCsQ5fk/l5vSd9eeTIVPWsAjmeRQNR2j1Ks/RC9/Amq5P74P6uQ==",
                            Type = 2,
                            Username = "180321055"
                        },
                        new
                        {
                            LoginId = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антони",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEO3GIUtaad7OUZpi4VvdMOiq6vVSlg1fC2/KJpwhY5r2sNbs1XQqkR71a8kMLa6C6w==",
                            Type = 2,
                            Username = "180321056"
                        },
                        new
                        {
                            LoginId = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Щилян",
                            NameLast = "Казаков",
                            Password = "AQAAAAEAACcQAAAAEHuHdA2A9aOAfgo23EnK1JRC8C9RiVlEpTKqXe+HkkJkcZAfKXr3BAlSiwuLkJjP5g==",
                            Type = 2,
                            Username = "180321057"
                        },
                        new
                        {
                            LoginId = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Парушев",
                            Password = "AQAAAAEAACcQAAAAEOqBwfi+gnKkzHjRpn00/S1jceX4ge/1Hp7keBt8ufej+sSkYKAOcS0DJdCNFAUnXA==",
                            Type = 2,
                            Username = "180321058"
                        },
                        new
                        {
                            LoginId = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Кратунова",
                            Password = "AQAAAAEAACcQAAAAECnf6aIE97CBG6k6V3h48sCGClz5WacerzEtLvsXr+BbjzFRejlnFaUpb3GDP5xHVQ==",
                            Type = 2,
                            Username = "180321059"
                        },
                        new
                        {
                            LoginId = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Спасимир",
                            NameLast = "Тричков",
                            Password = "AQAAAAEAACcQAAAAEAqFzca86kd4HQTVNLcWKe3H7dt1LyDoQAlCLDV4MGKB1vh0DeHztJ9OLOxYa9jgKw==",
                            Type = 2,
                            Username = "180321060"
                        },
                        new
                        {
                            LoginId = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Цачева",
                            Password = "AQAAAAEAACcQAAAAEEc+ox8G8vUTMHfZoCjK2hJC1j9k8eEF3fMmqifTIPAdCyXxDvgfPgVWWQqSbd4nhw==",
                            Type = 2,
                            Username = "180321061"
                        },
                        new
                        {
                            LoginId = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Екрем",
                            NameLast = "Дрянов",
                            Password = "AQAAAAEAACcQAAAAECdgadMnrzNP/wsPeJ0GtbI1Vmv3B15JZaf+FpymCyA4/DYB4f1JoqLRPZ2NKkWF+A==",
                            Type = 2,
                            Username = "180321062"
                        },
                        new
                        {
                            LoginId = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ричард",
                            NameLast = "Христов",
                            Password = "AQAAAAEAACcQAAAAENMRv8UiNkxd1cLJxObvF5rZo6K25ykgTVwpn276TrxvcHXT6SqBC0LUEqhak8PgvQ==",
                            Type = 2,
                            Username = "180321063"
                        },
                        new
                        {
                            LoginId = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дейвид",
                            NameLast = "Коуди",
                            Password = "AQAAAAEAACcQAAAAENiKMcKD5jWdtQAx3hUqdQZZ8fb+k/fez5aE8aLAmmTepM9/0OYZxnfR8S3za/+ZtQ==",
                            Type = 2,
                            Username = "180321064"
                        },
                        new
                        {
                            LoginId = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дарен",
                            NameLast = "Стоев",
                            Password = "AQAAAAEAACcQAAAAEBqTBYNbfXst7faIMKMehgNu9LitwYsVQD8uXywrdRLQ2eNtWgGd4fLgc6KmsBCA2w==",
                            Type = 2,
                            Username = "180321065"
                        },
                        new
                        {
                            LoginId = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йосиф",
                            NameLast = "Йозов",
                            Password = "AQAAAAEAACcQAAAAEAg2EerplJbP59rVvTG6c2iK3ph0SRIqFaBtk9Eepasv0+k1Sg3t3th1A8tkZ50ruw==",
                            Type = 2,
                            Username = "180321066"
                        },
                        new
                        {
                            LoginId = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Кондаков",
                            Password = "AQAAAAEAACcQAAAAEEstlvFRAxaVctrAMr58LadSkeU/kdhSz+NvUjsfB4iqUt64d2fKdih5erqXPOJaew==",
                            Type = 2,
                            Username = "180321067"
                        },
                        new
                        {
                            LoginId = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бианка",
                            NameLast = "Минева",
                            Password = "AQAAAAEAACcQAAAAEGUTWobLsnFCDpafKaCvn+76oSw2IMOFH9yqH04e57aeJ8iICTLHFBaajw9DrdhahA==",
                            Type = 2,
                            Username = "180321068"
                        },
                        new
                        {
                            LoginId = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEKpf44dwVZKxps7YadtcicGEdpauzl0TEizkEnz5DGN4oupNzhebc71y0B7HNF2ZHg==",
                            Type = 2,
                            Username = "180321069"
                        },
                        new
                        {
                            LoginId = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEFiYjtL1rQ3pGrs89Yh2U27/WXG1F5rT0sRvq+k+hir2d8h81bhchP9b/Yj8aa161w==",
                            Type = 2,
                            Username = "180321070"
                        },
                        new
                        {
                            LoginId = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Пейчев",
                            Password = "AQAAAAEAACcQAAAAENMCF1CUgMruFVux9swGHUx8DJFtpqghrHPkYaWD5/3dE0hNoKPInX5hakbU/JlrYA==",
                            Type = 2,
                            Username = "180321071"
                        },
                        new
                        {
                            LoginId = 73,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEKQK3vsv4CGCvD9IXEKckOE5YaoI9qYZF4z52Bc8Vtx/2SZ4nZPRmGb0X5WB5UnkOw==",
                            Type = 2,
                            Username = "180321072"
                        },
                        new
                        {
                            LoginId = 74,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Янев",
                            Password = "AQAAAAEAACcQAAAAEJP1/hP5WcXdY9BWZerxYx8IMX9e2W+X1IDEF2AaNDclyflSwYDL7/CVmYGoFovTKg==",
                            Type = 2,
                            Username = "180321073"
                        },
                        new
                        {
                            LoginId = 75,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Радостин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEDWjzSnpVkUy/YwLLyXCJoyU4+B0YQwyeb3aYk4Q0IR41PX3TgrC2ybYiQr+ozG9HQ==",
                            Type = 2,
                            Username = "180321074"
                        },
                        new
                        {
                            LoginId = 76,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Младенова",
                            Password = "AQAAAAEAACcQAAAAEBMd/5NAj5peChXyq6VQq25m9+iOO4EcPQzjxpBfvqWebRavjFIqvISPSp0sW5A7yQ==",
                            Type = 2,
                            Username = "180321075"
                        },
                        new
                        {
                            LoginId = 77,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Величка",
                            NameLast = "Стоянова",
                            Password = "AQAAAAEAACcQAAAAEAzVyRsfXA6YC8qTVuKYsxKo2by13pc3i/dG/a/90gg/Hfc+HlgMCj5fNitYJROtGQ==",
                            Type = 2,
                            Username = "180321076"
                        },
                        new
                        {
                            LoginId = 78,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Лъчезар",
                            NameLast = "Митев",
                            Password = "AQAAAAEAACcQAAAAEIKAr2AHl3mNTGY5BxcMrMYVNx/bq/ny0/dd0cujleTqVkBYVVEnu5ewb0iwL2yjcg==",
                            Type = 2,
                            Username = "180321077"
                        },
                        new
                        {
                            LoginId = 79,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Ангелова",
                            Password = "AQAAAAEAACcQAAAAEN0LiUX611sn9FbSpTqvgMKW6bKwuqSsu1B37MTyXIRYKhkvWfPGsRC+zxv/qiZSvw==",
                            Type = 2,
                            Username = "180321078"
                        },
                        new
                        {
                            LoginId = 80,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Хари",
                            NameLast = "Балабанов",
                            Password = "AQAAAAEAACcQAAAAEKP7uWa363MYS6YDpayN4Klrk00JEoickS0Wg7+zicVKGAFL3SRPCsUR7Km5uOXAWg==",
                            Type = 2,
                            Username = "180321079"
                        },
                        new
                        {
                            LoginId = 81,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Незиха",
                            NameLast = "Хаджиева",
                            Password = "AQAAAAEAACcQAAAAEB5vMMBX7hcCZTedK/OxkcsbMcLbkhCyvjcKIMYcDvUslXTdpnUayhupHxs4qUCtqg==",
                            Type = 2,
                            Username = "180321080"
                        },
                        new
                        {
                            LoginId = 82,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Недялков",
                            Password = "AQAAAAEAACcQAAAAECHVqtLPRt5GhPbwJ67tCmpCV41qmeIDEh7qwvQGT9nZZZoT3gPPUS0y76LBAJwUMg==",
                            Type = 2,
                            Username = "180321081"
                        },
                        new
                        {
                            LoginId = 83,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Костадин",
                            NameLast = "Запрянов",
                            Password = "AQAAAAEAACcQAAAAEEGqAVc7JpguFewQqN7x3JJEEg1IvR8p9aslwSKfsPpxsrlOiZ5VgWu4YYfx9de4+A==",
                            Type = 2,
                            Username = "180321082"
                        },
                        new
                        {
                            LoginId = 84,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриел",
                            NameLast = "Гигов",
                            Password = "AQAAAAEAACcQAAAAEEc6E8u1ykMJsqufLVeKKDb/LaE539JSNwL6eiqfF/KjmRp9p4uroSKQia1BFhE8VA==",
                            Type = 2,
                            Username = "180321083"
                        },
                        new
                        {
                            LoginId = 85,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEOLXp6orGrN11tzFthtvvD80B9C/+XMy3WPqmmvjXEvS1jA1mWIOY/bCK9g7rs3TNA==",
                            Type = 2,
                            Username = "180321084"
                        },
                        new
                        {
                            LoginId = 86,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Илиев",
                            Password = "AQAAAAEAACcQAAAAEH5iCYtOtJiKiN7XkbKhOgMjBT/oMEE/WikRB/L+ouXAQ+jcI4DQcWXNo2Pmwul+IA==",
                            Type = 2,
                            Username = "180321086"
                        },
                        new
                        {
                            LoginId = 87,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кристиян",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEGl1xl4xyeUNzU26imrvwfwi0c2XE3VL4hRTGbXrf2wgjsFEZdHJRddzNetwxe7wSA==",
                            Type = 2,
                            Username = "180321087"
                        },
                        new
                        {
                            LoginId = 88,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Кръстев",
                            Password = "AQAAAAEAACcQAAAAEDTWqs20hVeyv/qFLeeF8RJ1Y6FXkMfskFPy2h9W0rIKqcGwtx4lnEMpbMmLmW7fFw==",
                            Type = 2,
                            Username = "180321088"
                        },
                        new
                        {
                            LoginId = 89,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEEW3zhf+g8NQJTDQQu0EbrwKFNgxy7zDryErjM3mBhGHxG4bmv5a40Y+Kr1c6ckdrA==",
                            Type = 2,
                            Username = "180321089"
                        },
                        new
                        {
                            LoginId = 90,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Виктор",
                            NameLast = "Хаджиев",
                            Password = "AQAAAAEAACcQAAAAEDELf8vRof2RwmmmpfXHGr5v4Vsras7CAcJYjq8KH8CXw/Gypg2bnhS3RZBS51G6wg==",
                            Type = 2,
                            Username = "180321090"
                        },
                        new
                        {
                            LoginId = 91,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дилян",
                            NameLast = "Янков",
                            Password = "AQAAAAEAACcQAAAAELn1uy/iSKV61w+hFNEPa4YTYIJ7SLNle3K3fvNGvLjF06uPDnmQRprJ2n/Xypavfg==",
                            Type = 2,
                            Username = "180321091"
                        },
                        new
                        {
                            LoginId = 92,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Алекс",
                            NameLast = "Манолов",
                            Password = "AQAAAAEAACcQAAAAEAIBOmFoWtPf8vlAR0ZiUyRkFAjbEHUjOtOe18KnWs1AmT6hUw9sSWlQFIBaqpH45w==",
                            Type = 2,
                            Username = "180321092"
                        },
                        new
                        {
                            LoginId = 93,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ивелин",
                            NameLast = "Танев",
                            Password = "AQAAAAEAACcQAAAAEKwQkZ97PvGgSMdMIxiEGFQXX0RxiltnRxkipgVGG054cjtInF84tAmlpwjW2JLmkA==",
                            Type = 2,
                            Username = "180321093"
                        },
                        new
                        {
                            LoginId = 94,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валерий",
                            NameLast = "Шулика",
                            Password = "AQAAAAEAACcQAAAAEBywwj2/dAnixSX6idC2FLaQ3jlt5jNohhOd1E605QpfFG5PUujkQ4JZw1hUviY3Dw==",
                            Type = 2,
                            Username = "180321094"
                        },
                        new
                        {
                            LoginId = 95,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEC2/E26kEilgIGynx6TdkV5YkawfUJRdmEaKeieqyAP7CBbkd7x2mmHhikuodxa2iw==",
                            Type = 2,
                            Username = "180321095"
                        },
                        new
                        {
                            LoginId = 96,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валентин",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEFpRScYpU93b9Sz7ZYL8NLp4d9pTWB51bHcYADrLqz2W2PKDv/L5KqUwIJsVlfL5Tg==",
                            Type = 2,
                            Username = "180321096"
                        },
                        new
                        {
                            LoginId = 97,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Костов",
                            Password = "AQAAAAEAACcQAAAAEDB1SOqaHWe1PiIIpdMXfD/Uqi2eM1VaDnLBp7wj+AHoEGGAoxBfSIWk02v3HOf+Dw==",
                            Type = 2,
                            Username = "180321097"
                        },
                        new
                        {
                            LoginId = 98,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Владислав",
                            NameLast = "Владов",
                            Password = "AQAAAAEAACcQAAAAEB619jLS5UejsKsNzh1vGALO9r+f0JU7eO0pQ+ttORsYKCCT/Q03UCyLx526pit7Fw==",
                            Type = 2,
                            Username = "180321098"
                        },
                        new
                        {
                            LoginId = 99,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEHmJVgVoenmY3oAvgAgNZnP56IgLtttw/l8ec2alotGOnA/jvqy39obaw0mjQh/O5g==",
                            Type = 2,
                            Username = "180321099"
                        },
                        new
                        {
                            LoginId = 100,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Артем",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEFTCTWh7qi38TY7EvTc/w8QkaMOZjW1w6W6ceQRYShX84SUlm7Nz0ks1sJwhk3t2jw==",
                            Type = 2,
                            Username = "1803261100"
                        },
                        new
                        {
                            LoginId = 101,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дмитро",
                            NameLast = "Добрев",
                            Password = "AQAAAAEAACcQAAAAEEx8eUQ+Oz6aZHiPQZV8Q7kEeUtCu7DCGFnx/DOHjdKJfa6RUqtAnk0k4UFIZJPEcw==",
                            Type = 2,
                            Username = "1803261101"
                        },
                        new
                        {
                            LoginId = 102,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирило",
                            NameLast = "Безниско",
                            Password = "AQAAAAEAACcQAAAAEIbCd5Lkh3AMU7D4yqrpKpzGaPxMQmbMBzg8kWtQRa5ouXyrk5mFPfe+GUtHplCcnw==",
                            Type = 2,
                            Username = "1803261102"
                        },
                        new
                        {
                            LoginId = 103,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Биков",
                            Password = "AQAAAAEAACcQAAAAEO8mNdX8st/yYg3BpJwo0zFC24l51X2yP88oBeKNsdJNDo06RMwtXhkA5Oe0YfgAHg==",
                            Type = 2,
                            Username = "1803261104"
                        },
                        new
                        {
                            LoginId = 104,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илля",
                            NameLast = "Кирилив",
                            Password = "AQAAAAEAACcQAAAAEETq1B5zXTrEqlVb7O1SHHa4msyv1TtrIUqdHo5Dp5QmUa9Vm14fPdWUxtsiKJGziA==",
                            Type = 2,
                            Username = "1803261105"
                        },
                        new
                        {
                            LoginId = 105,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Сакали",
                            Password = "AQAAAAEAACcQAAAAEAsvu4bI94jbViWmdZEmgh8UX6st5w3en5s2QVUbaRq97d7+4XIl2FK5aPmL0CPdRA==",
                            Type = 2,
                            Username = "1803261106"
                        },
                        new
                        {
                            LoginId = 106,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Денис",
                            NameLast = "Репев",
                            Password = "AQAAAAEAACcQAAAAEOxfA6bGVrRYTjtGVFwY7DF8kTCy8g4RyRu6flB46xrw8nr9pBtdjjzmJgIiZj/1qg==",
                            Type = 2,
                            Username = "1803261108"
                        },
                        new
                        {
                            LoginId = 107,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Вълчанов",
                            Password = "AQAAAAEAACcQAAAAED/sRfPEPeWMC00epIXJhMstfHE384iI7/hmnG9WYQiywc2SQUhFBg3LOqZY3RTWLA==",
                            Type = 1,
                            Username = "nikiv"
                        });
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Login", "Login")
                        .WithMany("Attempts")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.HasOne("relc.Models.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
