// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relc.Data;

namespace relc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200516112229_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("relc.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("GradingScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("GradingScoreMin")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoundingMethod")
                        .HasColumnType("int");

                    b.Property<short>("ScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeLimitSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("relc.Models.ExamAttempt", b =>
                {
                    b.Property<int>("ExamAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeTaken")
                        .HasColumnType("smallint");

                    b.HasKey("ExamAttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("LoginId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("relc.Models.ExamAttemptAnswer", b =>
                {
                    b.Property<int>("ExamAttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamAttemptId")
                        .HasColumnType("int");

                    b.HasKey("ExamAttemptAnswerId");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("ExamAttemptAnswers");
                });

            modelBuilder.Entity("relc.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AlwaysAppear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ExamQuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("relc.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Mandingo",
                            NameLast = "The Great",
                            Password = "AQAAAAEAACcQAAAAEFAWFYUxquWvCgdzWeH/NDOnLw3vJyOy6DO8zYF9VJCvZ7HFJvmJtA91I6TnAky6wA==",
                            Type = 1,
                            Username = "mandingo"
                        },
                        new
                        {
                            LoginId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Станимир",
                            NameLast = "Стоянов",
                            Password = "AQAAAAEAACcQAAAAEJf1/MsEncLqhaChHnVZ5dC2ecBKyXYA+oKDYUifoR6j8f8Dkb+LDMFBRLxHCpV/eA==",
                            Type = 1,
                            Username = "brek"
                        },
                        new
                        {
                            LoginId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Бекирски",
                            Password = "AQAAAAEAACcQAAAAEPyhGb6W5WNXz6L0SxcB3oKFQy1XMkRuS/YOv2Z3Y44/DoyvtJFQu/9sNIvV8TgHqQ==",
                            Type = 2,
                            Username = "180321001"
                        },
                        new
                        {
                            LoginId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Желязков",
                            Password = "AQAAAAEAACcQAAAAEEL/5nxybA2qcXRsj31zi8+5PYL93JPLzf/Jo3B+rXtXAN96FwrK0J26MeadR7HZZQ==",
                            Type = 2,
                            Username = "180321002"
                        },
                        new
                        {
                            LoginId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иоан",
                            NameLast = "Аврамов",
                            Password = "AQAAAAEAACcQAAAAEMRYioSUZvxcisQZuv4Jomt31Bl4qmJJmMZLlqq+4sU/+uuY9sS0XXFji93jG/2MuQ==",
                            Type = 2,
                            Username = "180321003"
                        },
                        new
                        {
                            LoginId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мария",
                            NameLast = "Павлова",
                            Password = "AQAAAAEAACcQAAAAEJYPTwlILgWmJ3EbaGrX3wICFQxaF42Gt6XRqIqX0lChRYTOODgpcqqFIDgUjw1F5Q==",
                            Type = 2,
                            Username = "180321004"
                        },
                        new
                        {
                            LoginId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAELH8KoeE6Na7R/YswBcREbiEKi31hi9gnItkr3yOr+OROyQM96n/0/JA+TYolSY9AA==",
                            Type = 2,
                            Username = "180321005"
                        },
                        new
                        {
                            LoginId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невена",
                            NameLast = "Мандева",
                            Password = "AQAAAAEAACcQAAAAEIKwmJwZ5WN3QDg/u3CMG8rNvrBGh5mnubWmYtMB3wPfp2H3RSQIHoUUrCzOFHSGaA==",
                            Type = 2,
                            Username = "180321006"
                        },
                        new
                        {
                            LoginId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невелина",
                            NameLast = "Аладжова",
                            Password = "AQAAAAEAACcQAAAAEGfkHeTWROOpkukTGX4NlLTpGIjmX2KJDYlS1QSJT+Fi/Uh0ZDtpv6RiyJsjGsFaVw==",
                            Type = 2,
                            Username = "180321007"
                        },
                        new
                        {
                            LoginId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Стефан",
                            NameLast = "Кючуков",
                            Password = "AQAAAAEAACcQAAAAEIoXME+RiYW22VbYQLNYzG8v2mZfdYLZb4d4jF158VMBxfYuNSfaZU+5X5RzF3W7+A==",
                            Type = 2,
                            Username = "180321008"
                        },
                        new
                        {
                            LoginId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румен",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEPoxEF/jLH7wPXF2aT+in6Qv3Ch/bTbfM0itZDEXx1thj4csv6C7On1uPtt9hbtHgw==",
                            Type = 2,
                            Username = "180321009"
                        },
                        new
                        {
                            LoginId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Пачелийска",
                            Password = "AQAAAAEAACcQAAAAECMTAn0leBi0B6tVVg0rE+kDsWHXumsQRnitkBwWrtNEfsQQUpX3pZ+3bEjoFbRTVg==",
                            Type = 2,
                            Username = "180321010"
                        },
                        new
                        {
                            LoginId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емилия",
                            NameLast = "Назърова",
                            Password = "AQAAAAEAACcQAAAAEMMnWh93xiUq0KnztRCuV+r/JR27N1PzbJ+fch6jrTvwQofv/8FTvEwS8ujKVMFX0g==",
                            Type = 2,
                            Username = "180321011"
                        },
                        new
                        {
                            LoginId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Веселин",
                            NameLast = "Станчев",
                            Password = "AQAAAAEAACcQAAAAEHz9M9f9HBXe8LiueBa6yKypyt2zsKHvjZ4rbHLmCkW3N/VVWh0zdoyV7EvUA0uvLQ==",
                            Type = 2,
                            Username = "180321012"
                        },
                        new
                        {
                            LoginId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иван",
                            NameLast = "Иванов",
                            Password = "AQAAAAEAACcQAAAAEG46c1yOJYugIgj4++Nm3qnCjS5MaeOiBrv3CEHE4GVNNFfiUIVigPx+fZtnzRsWNQ==",
                            Type = 2,
                            Username = "180321014"
                        },
                        new
                        {
                            LoginId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирил",
                            NameLast = "Караколев",
                            Password = "AQAAAAEAACcQAAAAEK4tNF7W1hwpFwo0gkE/yq7M2oSioVHKaw9LuP2K+D8YAQbfiPGAouvtMY6/3KSQrw==",
                            Type = 2,
                            Username = "180321015"
                        },
                        new
                        {
                            LoginId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Маноела",
                            NameLast = "Неделчева",
                            Password = "AQAAAAEAACcQAAAAEPE1RhcMTgtyvZBnba9K0UCQiHIApvJTBejqh7QjaxmL+Nxcl7aHBi42uyzNN4vcUQ==",
                            Type = 2,
                            Username = "180321016"
                        },
                        new
                        {
                            LoginId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Айгюл",
                            NameLast = "Аптурахим",
                            Password = "AQAAAAEAACcQAAAAEEUZARLtZ9XG/cVmUdHnL6MFapItGNFRAVtTbgLVg8SmymY13REyx1tdN9rcLtkQJA==",
                            Type = 2,
                            Username = "180321017"
                        },
                        new
                        {
                            LoginId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Камен",
                            NameLast = "Трайков",
                            Password = "AQAAAAEAACcQAAAAEAhtAwM8e8pZkILTptIqGqcV78g+QeVkPmaK4UYyjCiAyqpYHkRSygM/b5Lwxnppxg==",
                            Type = 2,
                            Username = "180321018"
                        },
                        new
                        {
                            LoginId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румяна",
                            NameLast = "Мурлева",
                            Password = "AQAAAAEAACcQAAAAEL5oAnkV1YEdFoBpICebyYVXvaKXHuLt5GX8g0b6l/8ykBkRf91ReLCaP2fJuUQEdw==",
                            Type = 2,
                            Username = "180321019"
                        },
                        new
                        {
                            LoginId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антоан",
                            NameLast = "Майдозян",
                            Password = "AQAAAAEAACcQAAAAEKc6s6vBfdW8L9PewYwo5yBvXYSP2/Dn7slWxE/bkxGDDzjELUC5Jqu+HbYCvINy9w==",
                            Type = 2,
                            Username = "180321020"
                        },
                        new
                        {
                            LoginId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велислав",
                            NameLast = "Андонов",
                            Password = "AQAAAAEAACcQAAAAEEsF3iWzLDEv48Zp6a3vKnPEaoMupH4P0K/IXnjGKZCW172TNnQdiaOSa/LE8ehItg==",
                            Type = 2,
                            Username = "180321021"
                        },
                        new
                        {
                            LoginId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Данчев",
                            Password = "AQAAAAEAACcQAAAAEKSt5dwLdtsPvKjfTjEzHYoINDBUd3m6G0kcUFk0bdeWq/5ohzmyPPcXMRH52j3nOw==",
                            Type = 2,
                            Username = "180321022"
                        },
                        new
                        {
                            LoginId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Икимов",
                            Password = "AQAAAAEAACcQAAAAEC4Tf4acOJpF0IkNE6Nm0cIkM/uWpLFjSJ85IU3SMbFeI3o5/nhHm1ty8WMw5d6idQ==",
                            Type = 2,
                            Username = "180321023"
                        },
                        new
                        {
                            LoginId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Василев",
                            Password = "AQAAAAEAACcQAAAAEP2OPW3D7yBvrqEGDGlLeO7Rfu9wRqPRIpqvp2e3o1OOHTQAJrozlcSQEmJdywvlaw==",
                            Type = 2,
                            Username = "180321024"
                        },
                        new
                        {
                            LoginId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ирина",
                            NameLast = "Циркалова",
                            Password = "AQAAAAEAACcQAAAAEAPVbblQJwMcCiyFKd6+sBVjROlBNOXKrWE6UlaiEx0BGvKnfxQKcNVCaFz9byAodA==",
                            Type = 2,
                            Username = "180321025"
                        },
                        new
                        {
                            LoginId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Сидеров",
                            Password = "AQAAAAEAACcQAAAAEPEC2uBR8ZyIPq/3Xel8jw/e+tFb6VTTjooiqS8Pz0jZrvvIUfN9SMRT6hYdQCZQLQ==",
                            Type = 2,
                            Username = "180321026"
                        },
                        new
                        {
                            LoginId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Елиан",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEN1jymFfv6CAXJozUnMXJXRtPkOXqCr8qZV2TxG043Q28CTNbXP6fIy43+9w+drQWg==",
                            Type = 2,
                            Username = "180321027"
                        },
                        new
                        {
                            LoginId = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Росен",
                            NameLast = "Рунтев",
                            Password = "AQAAAAEAACcQAAAAEKRI3nCyysvB12Z6QEyEswtAc+P3FWMXnAUiLsxld6JICTDgpUtJ3rBUdrLYzfAQeg==",
                            Type = 2,
                            Username = "180321028"
                        },
                        new
                        {
                            LoginId = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Надежда",
                            NameLast = "Георгиева",
                            Password = "AQAAAAEAACcQAAAAEMTlsJbvjMHkeI1SShTkhJFJWJuQHO+tGdDin0/oBKKYHXoe660RxOUXkEzYf+BF3A==",
                            Type = 2,
                            Username = "180321029"
                        },
                        new
                        {
                            LoginId = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Узунов",
                            Password = "AQAAAAEAACcQAAAAEKvG5V8zyYQiqDBhv9Of7syZi1sxo4bG944liHKoMMlYcvRX5hR1Mh1tibP4sY+e7A==",
                            Type = 2,
                            Username = "180321030"
                        },
                        new
                        {
                            LoginId = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Маламов",
                            Password = "AQAAAAEAACcQAAAAEA+/W56Gah3aQhZs9RNyCVXetJQJg7rCr/lzhzwcg4w5zDPGaNlMIREJohgm478Qww==",
                            Type = 2,
                            Username = "180321031"
                        },
                        new
                        {
                            LoginId = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Даниел",
                            NameLast = "Леви",
                            Password = "AQAAAAEAACcQAAAAEHQ+L46PwgeOX+YSKU4TwIId6cgaqdQduw+vKvqHwfKQnTbL+8eHirru8ePAelJWqg==",
                            Type = 2,
                            Username = "180321032"
                        },
                        new
                        {
                            LoginId = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сабри",
                            NameLast = "Юмер",
                            Password = "AQAAAAEAACcQAAAAECOs2EpEry/umfGtvCYo0wf1Y2YdvovO9UF2swSdsETHxFO16whdPCFmPEvI7YbCxQ==",
                            Type = 2,
                            Username = "180321033"
                        },
                        new
                        {
                            LoginId = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бедреттин",
                            NameLast = "Бекир",
                            Password = "AQAAAAEAACcQAAAAEK1JS9max6klilHDN5LB9h9ec/3EOJwOOHODMSNu5wqJ4ymVNlwzAM3xjPnn9x1MXg==",
                            Type = 2,
                            Username = "180321034"
                        },
                        new
                        {
                            LoginId = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Боянов",
                            Password = "AQAAAAEAACcQAAAAEI/EFce0MJY4oJQD5mdkZUGNfC+HQ0V2SBm0DqlSwACvJkhLyvmJOsAyQpIBcRrWvQ==",
                            Type = 2,
                            Username = "180321035"
                        },
                        new
                        {
                            LoginId = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитрия",
                            NameLast = "Христева",
                            Password = "AQAAAAEAACcQAAAAEOEoN8XLAXrKwccYZarC5fb1jGUdA6CVqQg3+FQOLyc/EpGytqOEwxznUhQNRlZGQQ==",
                            Type = 2,
                            Username = "180321036"
                        },
                        new
                        {
                            LoginId = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Момчилова",
                            Password = "AQAAAAEAACcQAAAAEMltFeusunQjiTZSWglu/WeiIcxiPf9cNDWzh0GCTDtkms1OSc28LuuNaARte0PGXA==",
                            Type = 2,
                            Username = "180321037"
                        },
                        new
                        {
                            LoginId = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Бютюнев",
                            Password = "AQAAAAEAACcQAAAAEDaq3RYTiWZW0kCMeg4E8PIPdnO9O4KyMpNTOp0JvvR2kLYhQ418Z5iudK5yV0D0MA==",
                            Type = 2,
                            Username = "180321038"
                        },
                        new
                        {
                            LoginId = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Савова",
                            Password = "AQAAAAEAACcQAAAAEDS2pkLJciaqs2/UWGfBJDtm+PQc2fzEDL03mVdIsGDMQufXAFRdUL8JCvp48kk/fw==",
                            Type = 2,
                            Username = "180321039"
                        },
                        new
                        {
                            LoginId = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Калин",
                            NameLast = "Йержабек",
                            Password = "AQAAAAEAACcQAAAAEGXSz4PAR/YjZSKgBe2yX4LDc+lENAszFEZXD1U6Q/TF2zauieBBrnioMMet9aNqdQ==",
                            Type = 2,
                            Username = "180321040"
                        },
                        new
                        {
                            LoginId = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бурджу",
                            NameLast = "Бахри",
                            Password = "AQAAAAEAACcQAAAAEAyo1dHA4/Ov08JCmO/LKTHEshfDAuYDEZJLFpchMw4m+jsZpLMJPJ/1J3CYi4G3Fg==",
                            Type = 2,
                            Username = "180321041"
                        },
                        new
                        {
                            LoginId = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емил",
                            NameLast = "Пеев",
                            Password = "AQAAAAEAACcQAAAAEMiABuymILKfMjywLvYq4DKy37w/xJIFvhnXOVQAv7F6gLoaPYml7aAF1Vub1WeV4g==",
                            Type = 2,
                            Username = "180321042"
                        },
                        new
                        {
                            LoginId = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иванина",
                            NameLast = "Иванова",
                            Password = "AQAAAAEAACcQAAAAEJneXmlxN3cHZBCbLX0qgPGHcN/av4oZ+j6twxajrfrrxcR6eq/zh6O+7ieuSYS0Nw==",
                            Type = 2,
                            Username = "180321043"
                        },
                        new
                        {
                            LoginId = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Диян",
                            NameLast = "Недков",
                            Password = "AQAAAAEAACcQAAAAEBsLYU/20liydPoq1HSzkh3VBVnpouPHYRtzgiYmN8VS5dzemDCRvDhPmWXWAR1Sqw==",
                            Type = 2,
                            Username = "180321044"
                        },
                        new
                        {
                            LoginId = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Едис",
                            NameLast = "Хаджи",
                            Password = "AQAAAAEAACcQAAAAEBlyMVSSScPI6JRXByZNAY4whsU2DRrD4Si/8LSNyA7VAK+McKnKAtfBfPHOe18tRA==",
                            Type = 2,
                            Username = "180321045"
                        },
                        new
                        {
                            LoginId = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йоан",
                            NameLast = "Караманов",
                            Password = "AQAAAAEAACcQAAAAEPPPfmXHdrd9VuY2CBq+zEq4dV0SrQw0Ebnldgd7f6oxzrMDFk2kQuA4epE9nMjhLA==",
                            Type = 2,
                            Username = "180321046"
                        },
                        new
                        {
                            LoginId = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велизар",
                            NameLast = "Велев",
                            Password = "AQAAAAEAACcQAAAAEPAcnx+5CeLnVu5T6wUULbwd0FS2sFKrmFfb4mAQwSUwrtni7z6kWb6nvJ5go0uk8Q==",
                            Type = 2,
                            Username = "180321047"
                        },
                        new
                        {
                            LoginId = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Джан",
                            NameLast = "Махмуд",
                            Password = "AQAAAAEAACcQAAAAEEEffkUXk+DElTjg4FWZ11t32DyTJpQUVY8arnQHJ455Ioelov6G83sZedLp6xKVSw==",
                            Type = 2,
                            Username = "180321048"
                        },
                        new
                        {
                            LoginId = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Марияна",
                            NameLast = "Бояджиева",
                            Password = "AQAAAAEAACcQAAAAEPAg8O7leCQWJDvI/M+mXnH4mZqvASGv4/JE9P1hTSJRZM/6sNg0QnxPvncUav2RqQ==",
                            Type = 2,
                            Username = "180321049"
                        },
                        new
                        {
                            LoginId = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEMiYgI5jFKh5Xrt+/KTRCxgVQke31AdJGfP0OBvVk1A6cowAruPA32uYSD82uIkMRw==",
                            Type = 2,
                            Username = "180321050"
                        },
                        new
                        {
                            LoginId = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Мурджев",
                            Password = "AQAAAAEAACcQAAAAEBnrcwd7ZgVp7l4cjSV3DqjvFR9+yiYNF2eWbCkwfxwVhlf9h0n0vSjXuXhbWvDBcA==",
                            Type = 2,
                            Username = "180321051"
                        },
                        new
                        {
                            LoginId = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Андрий",
                            NameLast = "Ряпов",
                            Password = "AQAAAAEAACcQAAAAELQQYCBtrDV39vKAICcL9L7WEv0zc7/S5hWubhMDJpvGpY61ZQZGcGE92Z1kqYg+wA==",
                            Type = 2,
                            Username = "180321052"
                        },
                        new
                        {
                            LoginId = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Вейсел",
                            NameLast = "Русков",
                            Password = "AQAAAAEAACcQAAAAEKhBbwdVZyF8dc+93FD+MiGJg/4V4WPfw6/4i1sutB+44qT8SvbGDr5zRFqwTq4Llg==",
                            Type = 2,
                            Username = "180321053"
                        },
                        new
                        {
                            LoginId = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриела",
                            NameLast = "Михайлова",
                            Password = "AQAAAAEAACcQAAAAEId5TLVKbrXrrLfGFNdPvbSxWK6xyIVC8pLTg6ypmhTLfT9syiq+fsEHJ5O1Qj3ZtA==",
                            Type = 2,
                            Username = "180321054"
                        },
                        new
                        {
                            LoginId = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEL52CDJazxr0EfsFYH56QUsOYpU+y9io9AJCdRiGCninneKtSEmSQPkkHKHGoF2XEA==",
                            Type = 2,
                            Username = "180321055"
                        },
                        new
                        {
                            LoginId = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антони",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEHuUF/savqJS+wO7pzb+tpBXOZJjqSCEYfCDnFhryS1vSzG1G3tR400FEKKOPBQPSw==",
                            Type = 2,
                            Username = "180321056"
                        },
                        new
                        {
                            LoginId = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Щилян",
                            NameLast = "Казаков",
                            Password = "AQAAAAEAACcQAAAAEF1UwJlyRfJ8xTvxkLDCkDwFnWxMZSq92VvY0t/nAK3mzNqNpbSEUjdgP3/hBCLt0Q==",
                            Type = 2,
                            Username = "180321057"
                        },
                        new
                        {
                            LoginId = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Парушев",
                            Password = "AQAAAAEAACcQAAAAEGM7X49O7YKJ5CmY5HU9hQGO2d01XJliYPSvOyIwitX53IVL1n12u1DZxKHxXRAVhg==",
                            Type = 2,
                            Username = "180321058"
                        },
                        new
                        {
                            LoginId = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Кратунова",
                            Password = "AQAAAAEAACcQAAAAEMDJfgutzyb2I5t3CabFlUadPiD6WEBu4CcVsn81Wt6GKzBGQFWLjDvCz6jFcfofhg==",
                            Type = 2,
                            Username = "180321059"
                        },
                        new
                        {
                            LoginId = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Спасимир",
                            NameLast = "Тричков",
                            Password = "AQAAAAEAACcQAAAAEI0/Q91WG6e2CybIlwC015sF8GqHr8t1NsYbe0tFBuIhmYwCcFOlopVKIRkzgMwr8A==",
                            Type = 2,
                            Username = "180321060"
                        },
                        new
                        {
                            LoginId = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Цачева",
                            Password = "AQAAAAEAACcQAAAAED9WP+s92ZOobBxxwXJvh4QdV03N4Q93O8FOxsCNhVSpaR4J6kR+eedLn2xtzd6wDg==",
                            Type = 2,
                            Username = "180321061"
                        },
                        new
                        {
                            LoginId = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Екрем",
                            NameLast = "Дрянов",
                            Password = "AQAAAAEAACcQAAAAEKwBL4gLDig6aPqO0Byp9bOdnSaWYDZSFIOxJkjl452DtQERr6HK7+hd8r26Ym3WVA==",
                            Type = 2,
                            Username = "180321062"
                        },
                        new
                        {
                            LoginId = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ричард",
                            NameLast = "Христов",
                            Password = "AQAAAAEAACcQAAAAEFUAR52Bry61YsKbCo+xnIbE068YQMTuqteiS3P9i/vCBhX6ndeeSrEHYK6W1QgACA==",
                            Type = 2,
                            Username = "180321063"
                        },
                        new
                        {
                            LoginId = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дейвид",
                            NameLast = "Коуди",
                            Password = "AQAAAAEAACcQAAAAEOecEPpsl6352ELqZcrwhXKV3/XBIMloUc1TQ8WsB/fwLlriQPK1GGlelWv6LMIffA==",
                            Type = 2,
                            Username = "180321064"
                        },
                        new
                        {
                            LoginId = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дарен",
                            NameLast = "Стоев",
                            Password = "AQAAAAEAACcQAAAAEHQIDcf1tkH77YgVe5b0EnFY7zR9zLhXCp3ldo4sLdQb/EmibFUZq9YL1GlZZOGHww==",
                            Type = 2,
                            Username = "180321065"
                        },
                        new
                        {
                            LoginId = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йосиф",
                            NameLast = "Йозов",
                            Password = "AQAAAAEAACcQAAAAEBpG1xdqbQAuKdbum2JFvPyJ3NEnEeAkCwxultyJ5gupRu4YI3FGzFDh1C1Z5td4oQ==",
                            Type = 2,
                            Username = "180321066"
                        },
                        new
                        {
                            LoginId = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Кондаков",
                            Password = "AQAAAAEAACcQAAAAEC/H0n+RmEZFirZ9ZSWy7I7LCZHADa5G6kfgVdBbp+VwBhlYgvuIc2J2qww6YVJSXg==",
                            Type = 2,
                            Username = "180321067"
                        },
                        new
                        {
                            LoginId = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бианка",
                            NameLast = "Минева",
                            Password = "AQAAAAEAACcQAAAAECiIhQ9XslLlt1S8BGIYygIC4Gfd9fo8+9ZCPZut8BJuG2VA/+zD6hG15Zh30zzhJQ==",
                            Type = 2,
                            Username = "180321068"
                        },
                        new
                        {
                            LoginId = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEK5ZE+eGdYGaZ7YGsophxovl75phSrTvPP8wewuUwJiWP+H8D8mqmcinDEbykOQezA==",
                            Type = 2,
                            Username = "180321069"
                        },
                        new
                        {
                            LoginId = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAECI4lP8ZGi7xOpXIYhKkX/ohqyehSRhxA4JjCYuhA4JtCEHw48KzCb9DptAROGohKA==",
                            Type = 2,
                            Username = "180321070"
                        },
                        new
                        {
                            LoginId = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Пейчев",
                            Password = "AQAAAAEAACcQAAAAELOSCKNOjuNBasBXGE+je1WI8oqHk+wKodrTgGehzUvf2V9Z6YJSTU4pYTel1RXgsA==",
                            Type = 2,
                            Username = "180321071"
                        },
                        new
                        {
                            LoginId = 73,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEIYvGSwDC0J+jK1lCS2pg22C8aO+2MY5TVC7+6LzGFLPKDF8eqk1NAuYdSSX1wkDAg==",
                            Type = 2,
                            Username = "180321072"
                        },
                        new
                        {
                            LoginId = 74,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Янев",
                            Password = "AQAAAAEAACcQAAAAEMcIjyjbUJGOKN1+7pPG5cpxGTRHdfYxDQIcPfZ8V5vhwQCOwe2g6oUXUHWVK4/kTA==",
                            Type = 2,
                            Username = "180321073"
                        },
                        new
                        {
                            LoginId = 75,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Радостин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEF/WymKpUgjTQZRuFmOOZsA6juFf8gsLA563ZwGIdCa199qP/7Uz9lnnN8eZWvCGSQ==",
                            Type = 2,
                            Username = "180321074"
                        },
                        new
                        {
                            LoginId = 76,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Младенова",
                            Password = "AQAAAAEAACcQAAAAENeGiJ9YQoTnxWvyqhs675e5LD14RXXRh/3InB2uMnYxf+mUZwqaXGVDRHpAv6MYTg==",
                            Type = 2,
                            Username = "180321075"
                        },
                        new
                        {
                            LoginId = 77,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Величка",
                            NameLast = "Стоянова",
                            Password = "AQAAAAEAACcQAAAAEAmeV8vwT1Ni0EkRnNwo1pjXoRlU6BJhHcQOWvBBTP4BirsCNnMN12KlyIpq1qZ9Dg==",
                            Type = 2,
                            Username = "180321076"
                        },
                        new
                        {
                            LoginId = 78,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Лъчезар",
                            NameLast = "Митев",
                            Password = "AQAAAAEAACcQAAAAEBng96RSci48IhFyz9FWNNgtH7upAeoT971rdmPLYZ6jX7veNZb0QGcqPwbbYHAYBw==",
                            Type = 2,
                            Username = "180321077"
                        },
                        new
                        {
                            LoginId = 79,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Ангелова",
                            Password = "AQAAAAEAACcQAAAAEGRfrONjKcrx2rw6ryWRQGoWT26bUnQyD0ZnzxR5Tb7bzwEP2SeGquaqDvpMdEgCoQ==",
                            Type = 2,
                            Username = "180321078"
                        },
                        new
                        {
                            LoginId = 80,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Хари",
                            NameLast = "Балабанов",
                            Password = "AQAAAAEAACcQAAAAENuUlI7d0cfuI8tYD8h+MhIdsAYS08C3GYluqOWsFuCl3VttuU4D9L/jiY3JNUzPcA==",
                            Type = 2,
                            Username = "180321079"
                        },
                        new
                        {
                            LoginId = 81,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Незиха",
                            NameLast = "Хаджиева",
                            Password = "AQAAAAEAACcQAAAAEO3UbnJGJPCMzkHQKgWAi0/knumBAFKHFwlVRYxLNrbNnaNm9/WE+ijq6st2F1ns2w==",
                            Type = 2,
                            Username = "180321080"
                        },
                        new
                        {
                            LoginId = 82,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Недялков",
                            Password = "AQAAAAEAACcQAAAAEBPCOK7rh7VpfKjy9z4Zqegoh6AxvRZr2NtdB8vlg7J1ggnKqhAkChWdVEAdG1w23Q==",
                            Type = 2,
                            Username = "180321081"
                        },
                        new
                        {
                            LoginId = 83,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Костадин",
                            NameLast = "Запрянов",
                            Password = "AQAAAAEAACcQAAAAEFAkWL6Kf1hOiRS9HmikLEyaBLFEv1toOi2AhnEeerx5a06d0i4fDb0hMwdb2HXmQw==",
                            Type = 2,
                            Username = "180321082"
                        },
                        new
                        {
                            LoginId = 84,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриел",
                            NameLast = "Гигов",
                            Password = "AQAAAAEAACcQAAAAEHaAulfc9+SBtkWt3QeFvzTaDS8ib0lqMPlGLEEjU6vtDgeQTIX4n6Ts+9DhGPVeag==",
                            Type = 2,
                            Username = "180321083"
                        },
                        new
                        {
                            LoginId = 85,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEO0CIg0ydHpMX6YfU0b09tmpY9sxnpzDpFMihM4hQtjknIXTONO1nS3/m5TCCg8bLA==",
                            Type = 2,
                            Username = "180321084"
                        },
                        new
                        {
                            LoginId = 86,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Илиев",
                            Password = "AQAAAAEAACcQAAAAEJQYEf7/NKNwyJ3gHmRAhx1/U5hxW74fOw0sok6uB8iIwS4qjGlKRXsiDQ7dXQ6ydg==",
                            Type = 2,
                            Username = "180321086"
                        },
                        new
                        {
                            LoginId = 87,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кристиян",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEFzOT7awG2ohqtltrfDwkMkEyMgYaS9WzJthaWBAZss7VG0yP4tk24ARTDwSBB56uQ==",
                            Type = 2,
                            Username = "180321087"
                        },
                        new
                        {
                            LoginId = 88,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Кръстев",
                            Password = "AQAAAAEAACcQAAAAEJHxRa8g7iFU6nnWnmU9Ky8YrPX+/8Sr/S3F/uCpdHI0HPQmLx1J4E9PVQACf+fBqg==",
                            Type = 2,
                            Username = "180321088"
                        },
                        new
                        {
                            LoginId = 89,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEOVJpCTmG2wX7yxjTCsiQb8IXE6iz+vhThnqxFuyFjR8ax/sHvg9CyRwfQ+If8n0hg==",
                            Type = 2,
                            Username = "180321089"
                        },
                        new
                        {
                            LoginId = 90,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Виктор",
                            NameLast = "Хаджиев",
                            Password = "AQAAAAEAACcQAAAAEID0mqIlpbwDh5sYCQ7F4QphD97jjp7/Yf+0eSW/oJYrvUp1l+jl/ifR/EpZBol5Fw==",
                            Type = 2,
                            Username = "180321090"
                        },
                        new
                        {
                            LoginId = 91,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дилян",
                            NameLast = "Янков",
                            Password = "AQAAAAEAACcQAAAAEHtnSJOjA9oyZKKty3R22YSwe8pe90ydIfFSEvvU4WiQLFumw2wOKfaUbVcmaR397A==",
                            Type = 2,
                            Username = "180321091"
                        },
                        new
                        {
                            LoginId = 92,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Алекс",
                            NameLast = "Манолов",
                            Password = "AQAAAAEAACcQAAAAEKQfjDZgxGhxQlb4YdW4P3kj2t+cUXlW8Qm1UO3aB5zhEFiOAmUiIP+sg+w821zpSw==",
                            Type = 2,
                            Username = "180321092"
                        },
                        new
                        {
                            LoginId = 93,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ивелин",
                            NameLast = "Танев",
                            Password = "AQAAAAEAACcQAAAAEAodLGoZvQ47eKIzAN97ibg3wtodec1mm9Hpa1K2yY84FGBJ9hb9+CegiwI9Xyv6jw==",
                            Type = 2,
                            Username = "180321093"
                        },
                        new
                        {
                            LoginId = 94,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валерий",
                            NameLast = "Шулика",
                            Password = "AQAAAAEAACcQAAAAEAyN9sgs0xtrXDpqiO47NnTMmEWanwp1LDq0uxhaGoOud1qkV5kULWCNyB0j8fY7nw==",
                            Type = 2,
                            Username = "180321094"
                        },
                        new
                        {
                            LoginId = 95,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEP6UtnDECWcci1yVXrfvW5/bCjmrYfwOB8AqfAOcfzwdk5ByjMGGn77euGkjzX6iIQ==",
                            Type = 2,
                            Username = "180321095"
                        },
                        new
                        {
                            LoginId = 96,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валентин",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEBvqavIU9xuPQgMJjcJeXtxNUtHGqzcT4Qe+Vd3kU4WtnIx1xsuQRhFlrAkX+eHctw==",
                            Type = 2,
                            Username = "180321096"
                        },
                        new
                        {
                            LoginId = 97,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Костов",
                            Password = "AQAAAAEAACcQAAAAEFckg1xCRqpIJxUIXWjSpqwKTzp8ELsROWUSz8d37BE2ftnmzMe1PlVj2oGKhvkbmQ==",
                            Type = 2,
                            Username = "180321097"
                        },
                        new
                        {
                            LoginId = 98,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Владислав",
                            NameLast = "Владов",
                            Password = "AQAAAAEAACcQAAAAEC4HwK+CiS3ZoFLDb0hJCaWkHahPsnT1ukKXTIUl/AIllC2PjTJTn4l+LwEgkrZR4w==",
                            Type = 2,
                            Username = "180321098"
                        },
                        new
                        {
                            LoginId = 99,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAELEI1ucrSbMXGW7Qop3RkEUHh/0I1dEuLWFTp2Tbefe3inwXk2oe7W03vUyL5804oQ==",
                            Type = 2,
                            Username = "180321099"
                        },
                        new
                        {
                            LoginId = 100,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Артем",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEJYAP2qAzFvx3rBgImLHbgF+zLZea67IXsCxbu8mnDg/XOXVCsyjSe5Vv4vk2ld+cQ==",
                            Type = 2,
                            Username = "1803261100"
                        },
                        new
                        {
                            LoginId = 101,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дмитро",
                            NameLast = "Добрев",
                            Password = "AQAAAAEAACcQAAAAEMJB+1swI+BaKlPPw/o2NBUkXY+EbGjg+KPYz79luRVjsG4YTKyWYO/+/mmKEkXXKw==",
                            Type = 2,
                            Username = "1803261101"
                        },
                        new
                        {
                            LoginId = 102,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирило",
                            NameLast = "Безниско",
                            Password = "AQAAAAEAACcQAAAAEIg0VWJE7tUTVHj37XeaDLRvNdxHScNa5rv+a4o7NgeU+rWJwNYcUdsxcHcG2qDGkA==",
                            Type = 2,
                            Username = "1803261102"
                        },
                        new
                        {
                            LoginId = 103,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Биков",
                            Password = "AQAAAAEAACcQAAAAEOsi6u7xmsobWcd+M2ilPB/Gr3RzHHZtvkrfxSenG/BLw4uV34ETK/RBBos6hgl9ww==",
                            Type = 2,
                            Username = "1803261104"
                        },
                        new
                        {
                            LoginId = 104,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илля",
                            NameLast = "Кирилив",
                            Password = "AQAAAAEAACcQAAAAEL90bUvRNv1NZNUsHmOx67tABYasjwKA9WlBbogTcsd2oG+aUpdFtPH2ha3oUqEdvA==",
                            Type = 2,
                            Username = "1803261105"
                        },
                        new
                        {
                            LoginId = 105,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Сакали",
                            Password = "AQAAAAEAACcQAAAAEEhsWgJugHqk7Dsm3V+ph7l3vWcbmYpR9KgT/MxfRicG17FOQ9kSMfEe1C6lRb9BRQ==",
                            Type = 2,
                            Username = "1803261106"
                        },
                        new
                        {
                            LoginId = 106,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Денис",
                            NameLast = "Репев",
                            Password = "AQAAAAEAACcQAAAAEGa/e2zDqubK4q6kO6gHkmHUmdvuXtItsX+Ix4wBojOeE3FuDnBEzbdb3eaguYfLPg==",
                            Type = 2,
                            Username = "1803261108"
                        },
                        new
                        {
                            LoginId = 107,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Вълчанов",
                            Password = "AQAAAAEAACcQAAAAEI0L5fIKCz9HBt8M1ezzUyTslX0QzT389w6DTm17UIuqrikddZG5DpcehFm/INbEjA==",
                            Type = 1,
                            Username = "nikiv"
                        });
                });

            modelBuilder.Entity("relc.Models.ExamAttempt", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Login", "Login")
                        .WithMany("ExamsAttempts")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.ExamAttemptAnswer", b =>
                {
                    b.HasOne("relc.Models.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.ExamQuestion", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
