// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relc.Data;

namespace relc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200517121427_Initial5")]
    partial class Initial5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("GradeRounded")
                        .HasColumnType("smallint");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeTaken")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("LoginId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptAnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("relc.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("GradingScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("GradingScoreMin")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoundingMethod")
                        .HasColumnType("int");

                    b.Property<short>("ScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeLimitSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("relc.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Mandingo",
                            NameLast = "The Great",
                            Password = "AQAAAAEAACcQAAAAELeFyIM59/h27J8CYpjUxSr9aJBL0krxZl0RZEXikDGj9p6AGR2upKeBux98qrb8Bw==",
                            Type = 1,
                            Username = "mandingo"
                        },
                        new
                        {
                            LoginId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Станимир",
                            NameLast = "Стоянов",
                            Password = "AQAAAAEAACcQAAAAEIub9vtBeeCo4VMh90n13ZZ9kvCAzSZSjDuDKXE11lQJHif8vPrMTbfY0AoLGzqdSA==",
                            Type = 1,
                            Username = "brek"
                        },
                        new
                        {
                            LoginId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Бекирски",
                            Password = "AQAAAAEAACcQAAAAEL5/5t6BSTsS5ssamxQga+XcEJyf4nbm53WJQLBErif6zlxszqGBb/aONBBlPIvBiQ==",
                            Type = 2,
                            Username = "1801321001"
                        },
                        new
                        {
                            LoginId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Желязков",
                            Password = "AQAAAAEAACcQAAAAEGB7eeTLLdGREtlUMUy3pYlb8z28pfeBB2PlKbc9zVteXcOHjtca6HUnDS4nE0EM1g==",
                            Type = 2,
                            Username = "1801321002"
                        },
                        new
                        {
                            LoginId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иоан",
                            NameLast = "Аврамов",
                            Password = "AQAAAAEAACcQAAAAEDx5co0+LZCwK4+cTY9CpMlqvXc6dRAh+n8rxUf+woJ7d0shd7knaSKwo1WsEholyw==",
                            Type = 2,
                            Username = "1801321003"
                        },
                        new
                        {
                            LoginId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мария",
                            NameLast = "Павлова",
                            Password = "AQAAAAEAACcQAAAAEPMZ3KRoJ7eEYxpcjlY5N18xMk7zpI7W7aKvWqZFdRHMsLAUE9xR3RuDROFd2zvUCg==",
                            Type = 2,
                            Username = "1801321004"
                        },
                        new
                        {
                            LoginId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEA2nTBA2rXBGUGWW8wxdUxGGg+I+N/K5DNXaIaZxFbj8p3ffvcCYsEL0649I4QdSEg==",
                            Type = 2,
                            Username = "1801321005"
                        },
                        new
                        {
                            LoginId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невена",
                            NameLast = "Мандева",
                            Password = "AQAAAAEAACcQAAAAEIULqLsXiMbtuZ3ck7iOmoQkkImefTUoOGxzujBEsc58vFdsv9oZNsIcEzbQx1vZ/Q==",
                            Type = 2,
                            Username = "1801321006"
                        },
                        new
                        {
                            LoginId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невелина",
                            NameLast = "Аладжова",
                            Password = "AQAAAAEAACcQAAAAEOBjYLX/eTKu/zPo2DTeAcSIC/IGWtu8ZE494vVMA+C3IAjHAtmYQF9SLjXTVrwgvw==",
                            Type = 2,
                            Username = "1801321007"
                        },
                        new
                        {
                            LoginId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Стефан",
                            NameLast = "Кючуков",
                            Password = "AQAAAAEAACcQAAAAENtoMkL6LLwpxHpMelrA7YVPlAdWAybeBr8YWtkgvz7vaGLQocm5n8dKxrA0LZetTA==",
                            Type = 2,
                            Username = "1801321008"
                        },
                        new
                        {
                            LoginId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румен",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAENf0xmbzhGtDHfGrx6cGc8WpmJt7K0nECNBbTzhNpEvNWN3dXY22DXNki8/JMZ7vMg==",
                            Type = 2,
                            Username = "1801321009"
                        },
                        new
                        {
                            LoginId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Пачелийска",
                            Password = "AQAAAAEAACcQAAAAEHNo8ewVD57zUClcI3asgBa8UVV00Ni0VrZQMRXUcNdrlpHPApZmg9Qy5LE+U/Z4Iw==",
                            Type = 2,
                            Username = "1801321010"
                        },
                        new
                        {
                            LoginId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емилия",
                            NameLast = "Назърова",
                            Password = "AQAAAAEAACcQAAAAELKf+9p8SROApFsALehOVXfd3tAP0rmNhijnLvDWN2AsZP+tpkhEcdn/8haXUXbjIg==",
                            Type = 2,
                            Username = "1801321011"
                        },
                        new
                        {
                            LoginId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Веселин",
                            NameLast = "Станчев",
                            Password = "AQAAAAEAACcQAAAAEAEagDMvm6Rwzbg+m8GHIXhz/6nfc1/lQwAm1PT0QT6588/WpfZFi9qjUNPwb7ChuA==",
                            Type = 2,
                            Username = "1801321012"
                        },
                        new
                        {
                            LoginId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иван",
                            NameLast = "Иванов",
                            Password = "AQAAAAEAACcQAAAAENlsAiGd+TuZ4Mj0YfNEuEiWlBqL+pEsHNbv+xQAkz9aPjVFN86rtNkv1o3gw3ygjw==",
                            Type = 2,
                            Username = "1801321014"
                        },
                        new
                        {
                            LoginId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирил",
                            NameLast = "Караколев",
                            Password = "AQAAAAEAACcQAAAAELijmayxUpmHCWhyKHBbHX266czkpUp7XrLEIEMqKfrCUopyRD+TE1J1Ir/ce34YCQ==",
                            Type = 2,
                            Username = "1801321015"
                        },
                        new
                        {
                            LoginId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Маноела",
                            NameLast = "Неделчева",
                            Password = "AQAAAAEAACcQAAAAEO42FC7jT3poHae/nwcJLcTAJ2wY7T4RGupaIgB3zTjWxWff+vSSMvrGFuO65K0MrQ==",
                            Type = 2,
                            Username = "1801321016"
                        },
                        new
                        {
                            LoginId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Айгюл",
                            NameLast = "Аптурахим",
                            Password = "AQAAAAEAACcQAAAAEA4ukeuIPsE1mYL7vVjSZNl8Gf5f13uu83iQrfj4cgiEYiVCxzfGvLm987Vt3nFtjg==",
                            Type = 2,
                            Username = "1801321017"
                        },
                        new
                        {
                            LoginId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Камен",
                            NameLast = "Трайков",
                            Password = "AQAAAAEAACcQAAAAEEbtzZiQqtlWa51ZrjiKkE48TFhSRTRniwuXBm0uQjb3lkZod6G7Xv/j8O38KElRBw==",
                            Type = 2,
                            Username = "1801321018"
                        },
                        new
                        {
                            LoginId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румяна",
                            NameLast = "Мурлева",
                            Password = "AQAAAAEAACcQAAAAELapKk0hur89pFMH7S0GpnTtqOz0ctLUzT/PqsP9J5bdtx52yU0fRK3d/zsisR7Ipg==",
                            Type = 2,
                            Username = "1801321019"
                        },
                        new
                        {
                            LoginId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антоан",
                            NameLast = "Майдозян",
                            Password = "AQAAAAEAACcQAAAAECySTY63U5UWSWRiGA/HaIqbJW7f1FN//oKoLo7t/16uqoDdMJ1czl0xDcv2TV2HQQ==",
                            Type = 2,
                            Username = "1801321020"
                        },
                        new
                        {
                            LoginId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велислав",
                            NameLast = "Андонов",
                            Password = "AQAAAAEAACcQAAAAEAZVPCMfNFSVg9J4nMqXFflFDULwzHwgew0NIP0+AMw4qofKplL0rtdhjADOMVKPQg==",
                            Type = 2,
                            Username = "1801321021"
                        },
                        new
                        {
                            LoginId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Данчев",
                            Password = "AQAAAAEAACcQAAAAENp2GqN8qrHDVY2TaTrcA4eca206nU5kPUMRDdBEcglv7j7eR8QZ5NcczNLG/2kysw==",
                            Type = 2,
                            Username = "1801321022"
                        },
                        new
                        {
                            LoginId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Икимов",
                            Password = "AQAAAAEAACcQAAAAEIx5MoBHRTg580/Y5dK+F9mhs45DHlc0ByzAoyB2Wa34W5SIFbEf+w8mopQwitYwQg==",
                            Type = 2,
                            Username = "1801321023"
                        },
                        new
                        {
                            LoginId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Василев",
                            Password = "AQAAAAEAACcQAAAAEFydA2BgxZP9OICYKEvExSm15mXesR3Eh47v4SFQ8qrn1yhJLvyHDzNfLNuyc24pmw==",
                            Type = 2,
                            Username = "1801321024"
                        },
                        new
                        {
                            LoginId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ирина",
                            NameLast = "Циркалова",
                            Password = "AQAAAAEAACcQAAAAEMBkkJswfFLgELPboc9qMvEs4V9CbzUNv0lKkNKqhpF0mF0bZlqUWWCnYhwQe4S6XA==",
                            Type = 2,
                            Username = "1801321025"
                        },
                        new
                        {
                            LoginId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Сидеров",
                            Password = "AQAAAAEAACcQAAAAEGoQK/ZILlnYr2cOwqHQRuZ69vzQQ9M5hkM7swpiuXxVECDz9icQ0DITdAxRyyO3/g==",
                            Type = 2,
                            Username = "1801321026"
                        },
                        new
                        {
                            LoginId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Елиан",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEHe8fF2XrrY+/1WVClzlVDjr9FUCOoEfKKFOQbzzfPSQJmVmfGc6CAje50UzcGMDQQ==",
                            Type = 2,
                            Username = "1801321027"
                        },
                        new
                        {
                            LoginId = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Росен",
                            NameLast = "Рунтев",
                            Password = "AQAAAAEAACcQAAAAEGZmvOZnZRaAe9pVFwkZjURUFkHqVYXUXMO/jvzIQdo1Hfct7gd/fBe9g0HpBQoS8A==",
                            Type = 2,
                            Username = "1801321028"
                        },
                        new
                        {
                            LoginId = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Надежда",
                            NameLast = "Георгиева",
                            Password = "AQAAAAEAACcQAAAAEIv+CzSM2my3/PP00OQRxjRUoNWRZPEvHqG2X5yc2JTfEmXQLXK0zUnnoulg3T2eew==",
                            Type = 2,
                            Username = "1801321029"
                        },
                        new
                        {
                            LoginId = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Узунов",
                            Password = "AQAAAAEAACcQAAAAEAMD7P6pjvAQf6nFT9FqOVXKibLZqGhmEgzUvjphNlPPnt1oYSIYQb2aVHBHKVQqVw==",
                            Type = 2,
                            Username = "1801321030"
                        },
                        new
                        {
                            LoginId = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Маламов",
                            Password = "AQAAAAEAACcQAAAAEAacJVvyM8/lrDTc3L1R8NigDyxx1eLyAoZA8mVtuinf5nPCZRSocRQoEc9nNb3jEg==",
                            Type = 2,
                            Username = "1801321031"
                        },
                        new
                        {
                            LoginId = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Даниел",
                            NameLast = "Леви",
                            Password = "AQAAAAEAACcQAAAAENqG29ccpHydGd38yTN1uvSfWOpYts4Ec7QbwGico8ZWNjBn/70QbXQtlD41glS0CA==",
                            Type = 2,
                            Username = "1801321032"
                        },
                        new
                        {
                            LoginId = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сабри",
                            NameLast = "Юмер",
                            Password = "AQAAAAEAACcQAAAAEMJ6o4v6r8c47LiH17Y2ZXHSIGPn6G06m8PDmS+ljdntFbkHMI08lXddtw+6uBF31w==",
                            Type = 2,
                            Username = "1801321033"
                        },
                        new
                        {
                            LoginId = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бедреттин",
                            NameLast = "Бекир",
                            Password = "AQAAAAEAACcQAAAAEGCLPhfv/FK9xVc/V71xf+7ifxtxtb/aIqxR5GXmdLGkRvZPyVDpKTFnvZemANU7zg==",
                            Type = 2,
                            Username = "1801321034"
                        },
                        new
                        {
                            LoginId = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Боянов",
                            Password = "AQAAAAEAACcQAAAAEBm0NX7KTlMOc9krqcwTU42mOwxhByJvwAY44p3DQngmTYoJIzMs0/v69ztwDU+8wA==",
                            Type = 2,
                            Username = "1801321035"
                        },
                        new
                        {
                            LoginId = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитрия",
                            NameLast = "Христева",
                            Password = "AQAAAAEAACcQAAAAEN3OHksyJHWhiOkI8a6Pef4qIcyWWyXsQWn/nALHlYDA1aKCHHwt7xYUGQGxCUCIzA==",
                            Type = 2,
                            Username = "1801321036"
                        },
                        new
                        {
                            LoginId = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Момчилова",
                            Password = "AQAAAAEAACcQAAAAEB+R7pbqoM9eWqM4WbDvzdVrhravufwKvqM9dnAGfEX9d5w1E4WjesGT1VpNgW3ntw==",
                            Type = 2,
                            Username = "1801321037"
                        },
                        new
                        {
                            LoginId = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Бютюнев",
                            Password = "AQAAAAEAACcQAAAAEI+ba/0BzEWm/19NMdj1Wds8Tah0tJDAP4967BY+eqQ4XiyTF2iN3diXI0MBjFOPOg==",
                            Type = 2,
                            Username = "1801321038"
                        },
                        new
                        {
                            LoginId = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Савова",
                            Password = "AQAAAAEAACcQAAAAEOavgE9jtRaD+xJobOzYJntMPR0yCEI0QzzSY5sRNoVGfa02x4JyCj7wGWp/D4JYSw==",
                            Type = 2,
                            Username = "1801321039"
                        },
                        new
                        {
                            LoginId = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Калин",
                            NameLast = "Йержабек",
                            Password = "AQAAAAEAACcQAAAAEMpTijIgBzt/2C9kJ6cq1/9Xgjry87T0KrzfKL9S8A5Ha7KQ8vlQ7bzMxeQMooy/lA==",
                            Type = 2,
                            Username = "1801321040"
                        },
                        new
                        {
                            LoginId = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бурджу",
                            NameLast = "Бахри",
                            Password = "AQAAAAEAACcQAAAAEKYfREPvJfEhDb4rHp46CZfJHrM5tnfHkfQXmrj6vDg5qraTXthj4k698Rp2NumAiA==",
                            Type = 2,
                            Username = "1801321041"
                        },
                        new
                        {
                            LoginId = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емил",
                            NameLast = "Пеев",
                            Password = "AQAAAAEAACcQAAAAEI4Ft9mq4X8oVyQX6TrPyU0vIDKQIcnUJxIerET8IA+t6RIC3u6SetupbHbnVlTlhQ==",
                            Type = 2,
                            Username = "1801321042"
                        },
                        new
                        {
                            LoginId = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иванина",
                            NameLast = "Иванова",
                            Password = "AQAAAAEAACcQAAAAEF665/WF1yvCHbx72qoX2NzR9w5ygQnfiRmrH56y3KYeNEhmCTFqteaOPuTDaONXdg==",
                            Type = 2,
                            Username = "1801321043"
                        },
                        new
                        {
                            LoginId = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Диян",
                            NameLast = "Недков",
                            Password = "AQAAAAEAACcQAAAAEBYAwJQVvYM2zQAlJelK9KU72+Ouf37BpiKisbqN1nF9k1ir+XYUWwC1oDWde15D8Q==",
                            Type = 2,
                            Username = "1801321044"
                        },
                        new
                        {
                            LoginId = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Едис",
                            NameLast = "Хаджи",
                            Password = "AQAAAAEAACcQAAAAEGHWsKKTeOame5C+nUNwVphuOTsiXsslJz/oNy3L2w1p6zt5YWYWTCvMzmAswMyYTg==",
                            Type = 2,
                            Username = "1801321045"
                        },
                        new
                        {
                            LoginId = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йоан",
                            NameLast = "Караманов",
                            Password = "AQAAAAEAACcQAAAAEEZ6e7LM2X/xzcuplaEguQnFlRsbXslWfClAIqeNZK/AsajxPMVM1XBPi3hTXt0rPQ==",
                            Type = 2,
                            Username = "1801321046"
                        },
                        new
                        {
                            LoginId = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велизар",
                            NameLast = "Велев",
                            Password = "AQAAAAEAACcQAAAAEI4LhzkbeZEUUFRSOIdKCuZoBuo/YeRyglbuOSbL2SLdb2xsC3dF1R71roULLLwJkw==",
                            Type = 2,
                            Username = "1801321047"
                        },
                        new
                        {
                            LoginId = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Джан",
                            NameLast = "Махмуд",
                            Password = "AQAAAAEAACcQAAAAEIrmznTUB2KI8aqau23vpguPZ01n3eJe7qh+MF8j7ms4uqveoi2JBTdY+bLf+LEPiQ==",
                            Type = 2,
                            Username = "1801321048"
                        },
                        new
                        {
                            LoginId = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Марияна",
                            NameLast = "Бояджиева",
                            Password = "AQAAAAEAACcQAAAAEM8xMvNXzRmAzj90BPOy2fnMYbHUZ72oUJSWdXqgYGWS3e7Ng6xuKtBsNJqPk4qZLA==",
                            Type = 2,
                            Username = "1801321049"
                        },
                        new
                        {
                            LoginId = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEPs1ftq3UWST/DyXNo0/poNJ65pTWmxwns5xkO2huqoWaGeJzHloGoa66bPBTsm5CA==",
                            Type = 2,
                            Username = "1801321050"
                        },
                        new
                        {
                            LoginId = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Мурджев",
                            Password = "AQAAAAEAACcQAAAAELtYSioMG+JChgBOgEuGzQtzvdtgygSsF75QArKj9nzarAC7lS6mXKSPIuj9hxwujw==",
                            Type = 2,
                            Username = "1801321051"
                        },
                        new
                        {
                            LoginId = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Андрий",
                            NameLast = "Ряпов",
                            Password = "AQAAAAEAACcQAAAAEOXabih5YXhc31cG5NzUZFbArIRgTOfSV0mMjEwBxjyXvsxUB2RQHeqEo3aha2QHgw==",
                            Type = 2,
                            Username = "1801321052"
                        },
                        new
                        {
                            LoginId = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Вейсел",
                            NameLast = "Русков",
                            Password = "AQAAAAEAACcQAAAAENTU/m+G5PEny/vwDHKVcBmQMwq6zJTX6wndCdGFAw3AjBCEpMaQ8IDbsWbCiHeDUQ==",
                            Type = 2,
                            Username = "1801321053"
                        },
                        new
                        {
                            LoginId = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриела",
                            NameLast = "Михайлова",
                            Password = "AQAAAAEAACcQAAAAEDM5QDKigooFkkkm/BVpAs/a5E9a6EANQRbaWIN8QAfXKR1TjhU0BOrp3TyUPHZX3A==",
                            Type = 2,
                            Username = "1801321054"
                        },
                        new
                        {
                            LoginId = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEBasyjHKYIlb+uVUOU7XI9kURAlc5KC7cLCJvV/0aWyzVaNPLrzw7iPar/5RDmlmQQ==",
                            Type = 2,
                            Username = "1801321055"
                        },
                        new
                        {
                            LoginId = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антони",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEGrCHDpgdEaNiFNWfOWACO4tRzF8+5OJFRVzyhw+dTSUzMxpEl6A81c7K27o26QmdA==",
                            Type = 2,
                            Username = "1801321056"
                        },
                        new
                        {
                            LoginId = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Щилян",
                            NameLast = "Казаков",
                            Password = "AQAAAAEAACcQAAAAEBmKsBNztmtx9wmo3s9HPE2HYcXKsbWZ16RwR77HSFOBefbexG5kLcNlNq3CRgcH6g==",
                            Type = 2,
                            Username = "1801321057"
                        },
                        new
                        {
                            LoginId = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Парушев",
                            Password = "AQAAAAEAACcQAAAAENocnVtvzAxgsdlD92cv02oFQ3n7ul2ESMNt7dvCSXqd/qyqpSAkGvgkl9yBJE1Udg==",
                            Type = 2,
                            Username = "1801321058"
                        },
                        new
                        {
                            LoginId = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Кратунова",
                            Password = "AQAAAAEAACcQAAAAEMPtD0hwWWfaF2yVcI4nYj9eNEqfrDAAVyB1veCG/LC83bSLwp1yH/JhyyvWcro7fA==",
                            Type = 2,
                            Username = "1801321059"
                        },
                        new
                        {
                            LoginId = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Спасимир",
                            NameLast = "Тричков",
                            Password = "AQAAAAEAACcQAAAAEJkjCtJGk6yIhzWQFDThO+V1LKs+yVfXLjzNFnAAOHkyKEV69odKWLyAB9JK4UAXeQ==",
                            Type = 2,
                            Username = "1801321060"
                        },
                        new
                        {
                            LoginId = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Цачева",
                            Password = "AQAAAAEAACcQAAAAEJAOllFz7k0iJBvVo97SHN4YeVUSsIZ95aH2TN/y/sN4oK0/AAqAkXuWNZ0a3zmddA==",
                            Type = 2,
                            Username = "1801321061"
                        },
                        new
                        {
                            LoginId = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Екрем",
                            NameLast = "Дрянов",
                            Password = "AQAAAAEAACcQAAAAEBCIZqyCvXEJgW1tJPbDHCo1cQ2hP+r+ixaJHghPzOpWIQ//7HOS01dWzsokNOfQdw==",
                            Type = 2,
                            Username = "1801321062"
                        },
                        new
                        {
                            LoginId = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ричард",
                            NameLast = "Христов",
                            Password = "AQAAAAEAACcQAAAAEAjppq8nC2YECOHkNq2Y0ZZ4HB3lIxWQr6Vmo9Ro3rTyv+0UmVr959UzDtA+x95Wwg==",
                            Type = 2,
                            Username = "1801321063"
                        },
                        new
                        {
                            LoginId = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дейвид",
                            NameLast = "Коуди",
                            Password = "AQAAAAEAACcQAAAAEAB/8By3kvQNRYXjMQRll9VdXJBRJP2LnxrqOlxf9HgIyWIsrCOR5l7FQddW/MDDjw==",
                            Type = 2,
                            Username = "1801321064"
                        },
                        new
                        {
                            LoginId = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дарен",
                            NameLast = "Стоев",
                            Password = "AQAAAAEAACcQAAAAEGE3AIWgTD+cAUgC4IswRJUQRREGZcuL5jcVC93blCOHq3y5TjuiyXFUywW/LQbG+g==",
                            Type = 2,
                            Username = "1801321065"
                        },
                        new
                        {
                            LoginId = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йосиф",
                            NameLast = "Йозов",
                            Password = "AQAAAAEAACcQAAAAEOIff35VxeAG2OIwfDrK4KEv6osqGokpyZpJb66Ix9PjlCGogpT82EA9jBYkoHospQ==",
                            Type = 2,
                            Username = "1801321066"
                        },
                        new
                        {
                            LoginId = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Кондаков",
                            Password = "AQAAAAEAACcQAAAAEA6l26Oc+6OpmN1M4sYHXeIncJjQ4QogbgXIBhcdzKullHYC6DWMi9XWZNUTDklARg==",
                            Type = 2,
                            Username = "1801321067"
                        },
                        new
                        {
                            LoginId = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бианка",
                            NameLast = "Минева",
                            Password = "AQAAAAEAACcQAAAAEJaJo7A/NzfcHVjqIRtq5/uNc8J+zzndyS9S8/LU9H/tVhJhP3ql9Ai0fg2f/a6G3A==",
                            Type = 2,
                            Username = "1801321068"
                        },
                        new
                        {
                            LoginId = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEJu+odaVIDXq+XMfnYk00iIf2SaF6SCJqQdmKWutOet3UX1sWOUY9J85W5WoXyglEQ==",
                            Type = 2,
                            Username = "1801321069"
                        },
                        new
                        {
                            LoginId = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEKys1YvhcACtiSkXWdkpuOrcKRTHEPrg+fj6wJAKt/E6xrl0eBfo2XWVhe0k7wE+pw==",
                            Type = 2,
                            Username = "1801321070"
                        },
                        new
                        {
                            LoginId = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Пейчев",
                            Password = "AQAAAAEAACcQAAAAEOQBeI291HgMj8OFV6F/DsSrvIqq5lIYhyqjpm97zAbr194lFNK0WcVosnYQP9z6jw==",
                            Type = 2,
                            Username = "1801321071"
                        },
                        new
                        {
                            LoginId = 73,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEObuzheCTlAJXNVu1yjOS7UtQT9KVYC2F7UGDOHdek/3Vhy2/xn7vTtbmXBzV5fREg==",
                            Type = 2,
                            Username = "1801321072"
                        },
                        new
                        {
                            LoginId = 74,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Янев",
                            Password = "AQAAAAEAACcQAAAAEDpHWZc+s8Jcrql0Q9POqtZuCeTqXK4gHuwCzblz0JL52iXyxXGJ9e54gV56fXILUA==",
                            Type = 2,
                            Username = "1801321073"
                        },
                        new
                        {
                            LoginId = 75,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Радостин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEEhNs+2aAn9D8Df6h1lXJD6aGcsIf5D9X0933PHSqiwefOVXaU0qZ/0IOFcwgsjLYA==",
                            Type = 2,
                            Username = "1801321074"
                        },
                        new
                        {
                            LoginId = 76,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Младенова",
                            Password = "AQAAAAEAACcQAAAAEH0B7UBglPKUV/m9HqSa3mtn91EdTvnQEOtsa4ED9L4MMPYCG3zrTiWMYzMFKtofMw==",
                            Type = 2,
                            Username = "1801321075"
                        },
                        new
                        {
                            LoginId = 77,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Величка",
                            NameLast = "Стоянова",
                            Password = "AQAAAAEAACcQAAAAEE16uk/yi4xmgwf26bIfic6SfElKpVeRBuhkzfoBXxn3PTeIlq1ppN0sUkhopeSIQQ==",
                            Type = 2,
                            Username = "1801321076"
                        },
                        new
                        {
                            LoginId = 78,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Лъчезар",
                            NameLast = "Митев",
                            Password = "AQAAAAEAACcQAAAAECpuV0erH0RtrXFz38TAV+Kq2gCrADk7Q4HCSz+YCdSDy7Wv9BDHLKR7HJ5b7NX/8g==",
                            Type = 2,
                            Username = "1801321077"
                        },
                        new
                        {
                            LoginId = 79,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Ангелова",
                            Password = "AQAAAAEAACcQAAAAEKbyf+n9masu4KgItPqGnmDoR+uBfP2h4I2oRT2cRTToopLSqc6R0XLgIK2A610jdA==",
                            Type = 2,
                            Username = "1801321078"
                        },
                        new
                        {
                            LoginId = 80,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Хари",
                            NameLast = "Балабанов",
                            Password = "AQAAAAEAACcQAAAAEEkRWyv6T5lYSK3h/vHxG+f1wbtgjgc2wbQtxvMJ+ZUw2IZjMWMxxPsNcLsjJ8xRfA==",
                            Type = 2,
                            Username = "1801321079"
                        },
                        new
                        {
                            LoginId = 81,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Незиха",
                            NameLast = "Хаджиева",
                            Password = "AQAAAAEAACcQAAAAEFLK9UwqPkilfdow4lz5TiSWfhlwLs95TPrB05PQHwtTJ6GTq8MwWbx7pCEdBXkYxQ==",
                            Type = 2,
                            Username = "1801321080"
                        },
                        new
                        {
                            LoginId = 82,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Недялков",
                            Password = "AQAAAAEAACcQAAAAEL3J0eOOGys2D5UoD5SYT7nxL2mYN0JLxtuz/sfylTBTt7DQr6txsdnqjA0EN6d7FA==",
                            Type = 2,
                            Username = "1801321081"
                        },
                        new
                        {
                            LoginId = 83,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Костадин",
                            NameLast = "Запрянов",
                            Password = "AQAAAAEAACcQAAAAEF/SvIn2hXGcaD1+GTVS1dvnS7ABeNKfzFKSNoFzUYAxxX7Y+Ih6MhSpDWc7fjB3eQ==",
                            Type = 2,
                            Username = "1801321082"
                        },
                        new
                        {
                            LoginId = 84,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриел",
                            NameLast = "Гигов",
                            Password = "AQAAAAEAACcQAAAAEFOpWpCCxZ/caZFJDI6qMvlRUX/7n9j5+mQZJ7afXsrxI813l5Boy9Xy2lFF9T2mUw==",
                            Type = 2,
                            Username = "1801321083"
                        },
                        new
                        {
                            LoginId = 85,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEIDvGgmagRB+bCKBFFJhqeytjimkIVp573rpuBQtQtDaXDVcPInNVtxKtr3JPrE8AQ==",
                            Type = 2,
                            Username = "1801321084"
                        },
                        new
                        {
                            LoginId = 86,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Илиев",
                            Password = "AQAAAAEAACcQAAAAEKoqS2mZ3+giaktVDbAGCTqCicWOjdd/YEdekRxA9SQ5QJS8Vq+RqaydNB48afIhmg==",
                            Type = 2,
                            Username = "1801321086"
                        },
                        new
                        {
                            LoginId = 87,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кристиян",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEHCH2KsiKMli+uQFj4XR3XykYbfpb+8GxeajKX9HMoN/u5tC9l2e/ZnpWDkpSKI61g==",
                            Type = 2,
                            Username = "1801321087"
                        },
                        new
                        {
                            LoginId = 88,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Кръстев",
                            Password = "AQAAAAEAACcQAAAAED/K0ZZyT56xctKpHJwyF2vCVbibUuqhj1D9PPUlCkog8/t3oFb3yddqL4Oo92Cb/g==",
                            Type = 2,
                            Username = "1801321088"
                        },
                        new
                        {
                            LoginId = 89,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAENbk7id2pZGGRG2QHNixLiNJm6euJI29hmb5+mY45s/oz9Fv1UuAJkIB5b2OzOWhCQ==",
                            Type = 2,
                            Username = "1801321089"
                        },
                        new
                        {
                            LoginId = 90,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Виктор",
                            NameLast = "Хаджиев",
                            Password = "AQAAAAEAACcQAAAAELsXjHwTlkZtqQ4wJhB4WiOsbHlQwDxq99A5oI/kz04NGeIDOvgcX0Aoe6yOHV9hEg==",
                            Type = 2,
                            Username = "1801321090"
                        },
                        new
                        {
                            LoginId = 91,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дилян",
                            NameLast = "Янков",
                            Password = "AQAAAAEAACcQAAAAEI9nuj0KEWf9gYC4BkRvWic44J+ErHjHmeHmKZv56a/wLbRvI8BANx/UWP1LFM9cpQ==",
                            Type = 2,
                            Username = "1801321091"
                        },
                        new
                        {
                            LoginId = 92,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Алекс",
                            NameLast = "Манолов",
                            Password = "AQAAAAEAACcQAAAAEHHUoHg3R1/QgWFDBjq5JBt1GS8cszFl4RoHJQmWRh3BYCJW49yLjqQLsHQSLQ+OSg==",
                            Type = 2,
                            Username = "1801321092"
                        },
                        new
                        {
                            LoginId = 93,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ивелин",
                            NameLast = "Танев",
                            Password = "AQAAAAEAACcQAAAAECTZsavcET2GQwE5TO1Tt5CBf148wm0bjF5ZAX6JLKmGtpvkl++n+yhuYf+XuJJp+Q==",
                            Type = 2,
                            Username = "1801321093"
                        },
                        new
                        {
                            LoginId = 94,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валерий",
                            NameLast = "Шулика",
                            Password = "AQAAAAEAACcQAAAAEHEttX8016gTZ6Lu0DHR1lJn+c/qw4RFBO/EnN5yPTSWp6HGU5lRZScSqooOYoAzRw==",
                            Type = 2,
                            Username = "1801321094"
                        },
                        new
                        {
                            LoginId = 95,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEOwztaP1ydI+/OCe3CBf3DH8c0d/3IMBzyRePYR4aCAcE/CmSqes9vxQ05yq2GOHAw==",
                            Type = 2,
                            Username = "1801321095"
                        },
                        new
                        {
                            LoginId = 96,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валентин",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEBV5xihwbwsQcTvwu/r+amR3zIOkJUVgF8QlmlwrEeTIz0CQYjqVwf9FDt4rP7Pa5A==",
                            Type = 2,
                            Username = "1801321096"
                        },
                        new
                        {
                            LoginId = 97,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Костов",
                            Password = "AQAAAAEAACcQAAAAEEifdq6Aj8vjUKoKPn8N6Qe4U+Wg9dkElglDtNchas+9duDAa1eoUahDdrBnXPiW7A==",
                            Type = 2,
                            Username = "1801321097"
                        },
                        new
                        {
                            LoginId = 98,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Владислав",
                            NameLast = "Владов",
                            Password = "AQAAAAEAACcQAAAAEIDeGGk5HBwWHPrIMeo1kteZvh/VbAxlxiWtfKNGy2oq9hXoqUTNvZp28Ngn+KKiBQ==",
                            Type = 2,
                            Username = "1801321098"
                        },
                        new
                        {
                            LoginId = 99,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEORDfq2tfdmdE2OpraMbba5kffnrmIdaiDYk9t06UcicY4muZ8H932IMd3hknBKbqA==",
                            Type = 2,
                            Username = "1801321099"
                        },
                        new
                        {
                            LoginId = 107,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Вълчанов",
                            Password = "AQAAAAEAACcQAAAAEHoGDn/gb98Ba0UtqW0XHG1VfCdQ5R4IyolMsJNmAPOTIecor9uAwtvPblCePKRrBg==",
                            Type = 1,
                            Username = "nikiv"
                        });
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Login", "Login")
                        .WithMany("Attempts")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.HasOne("relc.Models.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
