// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relc.Data;

namespace relc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("GradeRounded")
                        .HasColumnType("smallint");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeTaken")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("LoginId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.HasKey("AttemptAnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("relc.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("GradingScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("GradingScoreMin")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoundingMethod")
                        .HasColumnType("int");

                    b.Property<short>("ScoreMax")
                        .HasColumnType("smallint");

                    b.Property<short>("TimeLimitSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("relc.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Mandingo",
                            NameLast = "The Great",
                            Password = "AQAAAAEAACcQAAAAEOKFVzPJ3//0d2Z1VRuhyLtmvsDGMWkiPxIUWQFIlr/UnmnpQi/BCLNmxw2jbAF9KQ==",
                            Type = 1,
                            Username = "mandingo"
                        },
                        new
                        {
                            LoginId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Станимир",
                            NameLast = "Стоянов",
                            Password = "AQAAAAEAACcQAAAAELA8IP0JWL2um0wawfSguydOQJH/k975bEnCrxYhKNPUHbh5wsDGCFue9xHhIRX8bg==",
                            Type = 1,
                            Username = "brek"
                        },
                        new
                        {
                            LoginId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Бекирски",
                            Password = "AQAAAAEAACcQAAAAEIjrOIfeY9GfS8m8n8CPa81l5XTkIS9jMrjZYX5HKrAla7ddhHJTy+RIfxe0qWhllA==",
                            Type = 2,
                            Username = "180321001"
                        },
                        new
                        {
                            LoginId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Желязков",
                            Password = "AQAAAAEAACcQAAAAEAhPSm7hyqEes3GGtfq8kpzgoNn1PE6AJOfzc2xqqqQPKloeWXIiaanT/cEVnTy94Q==",
                            Type = 2,
                            Username = "180321002"
                        },
                        new
                        {
                            LoginId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иоан",
                            NameLast = "Аврамов",
                            Password = "AQAAAAEAACcQAAAAEIkDWmj04hs7nsb/wi1iM7Ncw4pzGXFioVCUhG05cO43GznhZAz/M4p67LbsitfjvQ==",
                            Type = 2,
                            Username = "180321003"
                        },
                        new
                        {
                            LoginId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мария",
                            NameLast = "Павлова",
                            Password = "AQAAAAEAACcQAAAAED5jC8s1ZZi9XPZfKDURR36t4Y1KaO2k7qKiiSYlcAHD+2a8S/yGnjdPe6pDNomycg==",
                            Type = 2,
                            Username = "180321004"
                        },
                        new
                        {
                            LoginId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAELVv1kPE/8nNwkcAsVvjqSd4lhb3LJ4tfyOYKn8+Agj1iGtBHXVmr7dMrwRcKJEsoQ==",
                            Type = 2,
                            Username = "180321005"
                        },
                        new
                        {
                            LoginId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невена",
                            NameLast = "Мандева",
                            Password = "AQAAAAEAACcQAAAAENp3Yo7P/PCD6j+cGdRIuW09poc0gz7WEW63o+6hsIbet+Ik60XKS0hKrrz6w6BKrg==",
                            Type = 2,
                            Username = "180321006"
                        },
                        new
                        {
                            LoginId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Невелина",
                            NameLast = "Аладжова",
                            Password = "AQAAAAEAACcQAAAAEHA1buzuCM9+f4T5pPz+GaV5wxkaUBUoXxIu0mKpmzF6w3Gf2v7ghXj2JrYO6V7Log==",
                            Type = 2,
                            Username = "180321007"
                        },
                        new
                        {
                            LoginId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Стефан",
                            NameLast = "Кючуков",
                            Password = "AQAAAAEAACcQAAAAEFeQP8ayR4dwCjofjlQD7Fwii9+LmeT/IxdXQEVn1dYLBkrMxexBYv47aUlMhlJcSQ==",
                            Type = 2,
                            Username = "180321008"
                        },
                        new
                        {
                            LoginId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румен",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEEpuPiqoetqrwFOEhgrAZMHXvBx2/etwi5FX2ikV6RmTpe2jeGCTElcA5L3jfDsqzQ==",
                            Type = 2,
                            Username = "180321009"
                        },
                        new
                        {
                            LoginId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Пачелийска",
                            Password = "AQAAAAEAACcQAAAAEPkHUyJ9+XhJHa/n6vy5KhgXEe5c61HiCOqqhWPAL6KJxD1VuHNhCvK7lUVUPIzWEw==",
                            Type = 2,
                            Username = "180321010"
                        },
                        new
                        {
                            LoginId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емилия",
                            NameLast = "Назърова",
                            Password = "AQAAAAEAACcQAAAAEB8DnSFWFnS5cfMKagX313emIWiVQgz44Zs6HCy2Bh6VNBCyViWF6excuemOre11OQ==",
                            Type = 2,
                            Username = "180321011"
                        },
                        new
                        {
                            LoginId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Веселин",
                            NameLast = "Станчев",
                            Password = "AQAAAAEAACcQAAAAEKjGg64F9yQXOxfD6QZF8hjSrzi44w0bPHTaFaFOmDxO3vYMmq2uYnaEVApnl/BIBg==",
                            Type = 2,
                            Username = "180321012"
                        },
                        new
                        {
                            LoginId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иван",
                            NameLast = "Иванов",
                            Password = "AQAAAAEAACcQAAAAEC7NxagWsqQTG42LOcIKqlPo+MBgLS5zDnnWSuL3TShd6erI+7FZRl3szycgN+IYUQ==",
                            Type = 2,
                            Username = "180321014"
                        },
                        new
                        {
                            LoginId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирил",
                            NameLast = "Караколев",
                            Password = "AQAAAAEAACcQAAAAEOQc2Fh1BReXYpa9SxfiFFORIuuGAQhSBKhMV5cklSMJsLJuhgBJe72f92KPsJy6eg==",
                            Type = 2,
                            Username = "180321015"
                        },
                        new
                        {
                            LoginId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Маноела",
                            NameLast = "Неделчева",
                            Password = "AQAAAAEAACcQAAAAEFueaRAXByY4RMhdWULiv9aPIZ7v+nPXWPf3unpeQnU83pmdE6kXvnm0Qqc/BOq3Zg==",
                            Type = 2,
                            Username = "180321016"
                        },
                        new
                        {
                            LoginId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Айгюл",
                            NameLast = "Аптурахим",
                            Password = "AQAAAAEAACcQAAAAEMvpJ6+016MVmuf0Tv3A/PC87t/npL0ilbrCjCEsGW6f8iefXaFfQj/2xoGTe2az+w==",
                            Type = 2,
                            Username = "180321017"
                        },
                        new
                        {
                            LoginId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Камен",
                            NameLast = "Трайков",
                            Password = "AQAAAAEAACcQAAAAEApVv9zXIuTsoXW0zyqNlqVW/bemgmHNU06OEpabq4nTwLYyxJzh2gyhxhMYIn2fmg==",
                            Type = 2,
                            Username = "180321018"
                        },
                        new
                        {
                            LoginId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Румяна",
                            NameLast = "Мурлева",
                            Password = "AQAAAAEAACcQAAAAEP20TwpT3MmufLXK5fhuuddUu6puEgkA4kHwLYA1cPekj7RbT57ylLZHUR4I9dfbOA==",
                            Type = 2,
                            Username = "180321019"
                        },
                        new
                        {
                            LoginId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антоан",
                            NameLast = "Майдозян",
                            Password = "AQAAAAEAACcQAAAAEAqtU3+3hV1Zz1+rMjlsVRY6/PB1barq4qeHultADNMKMeFwNxRJaub6msg3t2Dadw==",
                            Type = 2,
                            Username = "180321020"
                        },
                        new
                        {
                            LoginId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велислав",
                            NameLast = "Андонов",
                            Password = "AQAAAAEAACcQAAAAEAb+R0ZSI6yWN9chtV1r8HhpRpLPXsEuOQfPBSgVw5O1GydyO0HK9+gIUSC4pXP0pw==",
                            Type = 2,
                            Username = "180321021"
                        },
                        new
                        {
                            LoginId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Данчев",
                            Password = "AQAAAAEAACcQAAAAELNukqtdmUGsAo3B/xx4YfE98JOZQa7mq4O9sk8R4rPm02oPGE+h4nBEKXgdj2yi4Q==",
                            Type = 2,
                            Username = "180321022"
                        },
                        new
                        {
                            LoginId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Икимов",
                            Password = "AQAAAAEAACcQAAAAECGp60lwzXijOpp62f6r27I1mQProJbjM7+Wii89xS35DyoqflyEwuFbDM5EQRQEmA==",
                            Type = 2,
                            Username = "180321023"
                        },
                        new
                        {
                            LoginId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Мартин",
                            NameLast = "Василев",
                            Password = "AQAAAAEAACcQAAAAEN00sK9CQUrBIV1ThwLH1Y+eGn8holwe+iJcJ7sy62EzeQpYoHXE0WJQA53VaNBF/A==",
                            Type = 2,
                            Username = "180321024"
                        },
                        new
                        {
                            LoginId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ирина",
                            NameLast = "Циркалова",
                            Password = "AQAAAAEAACcQAAAAEBhdv5r7tesfRi4oqwDiY2bmXaO07LN4oMEC5RpvT9Q/F7WKEgpu6DomxI+V5XvPmw==",
                            Type = 2,
                            Username = "180321025"
                        },
                        new
                        {
                            LoginId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Сидеров",
                            Password = "AQAAAAEAACcQAAAAEEIctbJ6+yDnzy2qokbbEkWHDn/+jlp83HG0rbuk3KP34tIZ9L5fqStAUFo2AbsZhQ==",
                            Type = 2,
                            Username = "180321026"
                        },
                        new
                        {
                            LoginId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Елиан",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEIFCPTJPPnFXcmOlOmy42ScYj+IBHCwlqRVDV+JCeyxZR94pMvBwusUptaMWTAWKsA==",
                            Type = 2,
                            Username = "180321027"
                        },
                        new
                        {
                            LoginId = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Росен",
                            NameLast = "Рунтев",
                            Password = "AQAAAAEAACcQAAAAEDb3U2/m0mtsW2eQfD6gmuqv3H2/0Tu3IKAe+aoC94raBd6ZUE2gqjtLecEv2uek7A==",
                            Type = 2,
                            Username = "180321028"
                        },
                        new
                        {
                            LoginId = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Надежда",
                            NameLast = "Георгиева",
                            Password = "AQAAAAEAACcQAAAAEAg2Nj9ejHxoTbNKau7bw2B7xUiAlNlmikusi4GZLCFxjd4R8pP9NGsu7m/Ni3aADg==",
                            Type = 2,
                            Username = "180321029"
                        },
                        new
                        {
                            LoginId = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Узунов",
                            Password = "AQAAAAEAACcQAAAAEA6mlPROOgnJ9tlO38f7IBqLl3B5v3GPpKAkZgY4Y3tkLH8/JLZiDTUhd48KJWccYA==",
                            Type = 2,
                            Username = "180321030"
                        },
                        new
                        {
                            LoginId = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Маламов",
                            Password = "AQAAAAEAACcQAAAAEHy3V35XlQbY6DP3qFYSuRBDjrzu53mS0FzX7CFWkWvAfLWhMi24JZ9/43h4gmlsAA==",
                            Type = 2,
                            Username = "180321031"
                        },
                        new
                        {
                            LoginId = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Даниел",
                            NameLast = "Леви",
                            Password = "AQAAAAEAACcQAAAAEFb9ILd7bawXiZFITp8z4ScrUeDu10hfpxEIA6hws/BhmTVp8+M0nIiHD+vdgfAQVQ==",
                            Type = 2,
                            Username = "180321032"
                        },
                        new
                        {
                            LoginId = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сабри",
                            NameLast = "Юмер",
                            Password = "AQAAAAEAACcQAAAAEGXu/WWsxcksDY0e0IqQ/BkHaDhe+CKjp9z2v4kPmohoRNbKYEfAMAOR/w3ApWEESQ==",
                            Type = 2,
                            Username = "180321033"
                        },
                        new
                        {
                            LoginId = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бедреттин",
                            NameLast = "Бекир",
                            Password = "AQAAAAEAACcQAAAAEJfO17qPT7orKzVLfDbwCOkrPp0wWX4ajmM/BJpTYXzvcVeDsG16FrmU3agtHz+srg==",
                            Type = 2,
                            Username = "180321034"
                        },
                        new
                        {
                            LoginId = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Боянов",
                            Password = "AQAAAAEAACcQAAAAEMIlf9gGNp9A7tER1Gb5v5Y4bVUzyZdwr8d+WtLr28z9R2t0h18VlUFvkBZZG1PrLw==",
                            Type = 2,
                            Username = "180321035"
                        },
                        new
                        {
                            LoginId = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитрия",
                            NameLast = "Христева",
                            Password = "AQAAAAEAACcQAAAAECrY+LX5Qw8vdGLUUC0FQzqi9MrC/jhd/uu9JFKiKhRyZgblC8amtHzNJAaxOfnHSw==",
                            Type = 2,
                            Username = "180321036"
                        },
                        new
                        {
                            LoginId = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Тони",
                            NameLast = "Момчилова",
                            Password = "AQAAAAEAACcQAAAAEP1g8EymjYZiS3wCv7G1VF4HC9ReBT9Ivhx/sW31pMZlhaL/Y1zuQQznBCxESVe/8Q==",
                            Type = 2,
                            Username = "180321037"
                        },
                        new
                        {
                            LoginId = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Бютюнев",
                            Password = "AQAAAAEAACcQAAAAEOhzMLwlHRObARs4/URsUC6+3iR/wI36wvA2jkT9T2BzzVc6V6kvb29uIAkGt0U9fQ==",
                            Type = 2,
                            Username = "180321038"
                        },
                        new
                        {
                            LoginId = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Савова",
                            Password = "AQAAAAEAACcQAAAAEAT+s5taeCtF69fOkHw1LZa06O2ZIFM4hE7QnOnrMoLFfGchtAU1x+1O7PN/gptLlg==",
                            Type = 2,
                            Username = "180321039"
                        },
                        new
                        {
                            LoginId = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Калин",
                            NameLast = "Йержабек",
                            Password = "AQAAAAEAACcQAAAAECp0mn6wuBoc45sWMq+oPiF6tu89aE+elTZtwad2uRe2jQQh6qk4HOZ2DskLCRIo6w==",
                            Type = 2,
                            Username = "180321040"
                        },
                        new
                        {
                            LoginId = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бурджу",
                            NameLast = "Бахри",
                            Password = "AQAAAAEAACcQAAAAEHiO2cuJfdg6l3NnpeSQ9VmE09bUME/L5EZ55ET/UPjb7gw4mDrwMxMdpbBpCS5aDA==",
                            Type = 2,
                            Username = "180321041"
                        },
                        new
                        {
                            LoginId = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Емил",
                            NameLast = "Пеев",
                            Password = "AQAAAAEAACcQAAAAEJBUzdVsJUL2+gCl/dIz1mE2aEIXwTH3l/64yJRI4ONvzIah/GcIPMWOI4hTD2/BEw==",
                            Type = 2,
                            Username = "180321042"
                        },
                        new
                        {
                            LoginId = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Иванина",
                            NameLast = "Иванова",
                            Password = "AQAAAAEAACcQAAAAEJN/CcuTNrAqb/6JAzQNapHFpbsXYKJnsUgWSlecplyFHh1AmxTTZicTjWLA2EMnqw==",
                            Type = 2,
                            Username = "180321043"
                        },
                        new
                        {
                            LoginId = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Диян",
                            NameLast = "Недков",
                            Password = "AQAAAAEAACcQAAAAEPourr1KxlAZZrAKmYerGxP75Db6S22T+6sdv0vwMmNe5r/WYoNhs5JxLhokajoMXQ==",
                            Type = 2,
                            Username = "180321044"
                        },
                        new
                        {
                            LoginId = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Едис",
                            NameLast = "Хаджи",
                            Password = "AQAAAAEAACcQAAAAEKaOS6xXrnA42S/UQK6e57Iqb4nwOec3/M2W9QNtDycxtl/cFjirtvYgG9bPEHH7kA==",
                            Type = 2,
                            Username = "180321045"
                        },
                        new
                        {
                            LoginId = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йоан",
                            NameLast = "Караманов",
                            Password = "AQAAAAEAACcQAAAAEINA8dxlUPvUeRB3UUgcFFWt15OM58vVy5tyaP6Xlg7gYIE/7gh8QSj0BizgPj12qQ==",
                            Type = 2,
                            Username = "180321046"
                        },
                        new
                        {
                            LoginId = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Велизар",
                            NameLast = "Велев",
                            Password = "AQAAAAEAACcQAAAAEJo6UKcNcBVjKtEhhbrIHgAGAPw8GKiWRjm6yj5+724x9Jz+P8TLy5sekI3KcxxloA==",
                            Type = 2,
                            Username = "180321047"
                        },
                        new
                        {
                            LoginId = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Джан",
                            NameLast = "Махмуд",
                            Password = "AQAAAAEAACcQAAAAEOyaY2OVUrM89Tz/lkPBvPzb0llUCIOl5LYoGh/ACvmU8GGqD82BB6VvUIpY2hn6Iw==",
                            Type = 2,
                            Username = "180321048"
                        },
                        new
                        {
                            LoginId = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Марияна",
                            NameLast = "Бояджиева",
                            Password = "AQAAAAEAACcQAAAAEM924LqSFyNGyOT+2CmTLygrZO0U/uHpLol6MrM11MoIFmUHNfA+aQix1z02nqjB4Q==",
                            Type = 2,
                            Username = "180321049"
                        },
                        new
                        {
                            LoginId = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Никола",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAELYJ+RP0WEQSqGnDv8aM6/CWVHgtTH3xNhft+4ZoFMKAZ4M9zLGE9eEJ7MBbP88tBA==",
                            Type = 2,
                            Username = "180321050"
                        },
                        new
                        {
                            LoginId = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Мурджев",
                            Password = "AQAAAAEAACcQAAAAEJcKe2PNnPalUV5BcpTMO5dDvwWerk3E7c1BGVaNB//RoEoSpjGsnGPVbOLyYTk8fA==",
                            Type = 2,
                            Username = "180321051"
                        },
                        new
                        {
                            LoginId = 53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Андрий",
                            NameLast = "Ряпов",
                            Password = "AQAAAAEAACcQAAAAELXfWaYkY0mrluRub5jru7IjIOCawBi6+/JYaEl3fp7NFZ6dwk4TRUoYAJckI4bGdw==",
                            Type = 2,
                            Username = "180321052"
                        },
                        new
                        {
                            LoginId = 54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Вейсел",
                            NameLast = "Русков",
                            Password = "AQAAAAEAACcQAAAAEGg7C1bz+v0eWIXdxu7oFtPsd3p9e+4clwCJVxVDVaon8IoImJAlFv3lP0+ucEfCrA==",
                            Type = 2,
                            Username = "180321053"
                        },
                        new
                        {
                            LoginId = 55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриела",
                            NameLast = "Михайлова",
                            Password = "AQAAAAEAACcQAAAAEBiiA/w9GLK535a5lsSpA7u3ziIy4fSiAzGnH6D+duMwk5055NL8E69kIVhzr0uLvA==",
                            Type = 2,
                            Username = "180321054"
                        },
                        new
                        {
                            LoginId = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEPdmFpojyWt90i1YXAMIUfcAtkiI0n6dfeCLJqfyJBN9M8poeclh9x8noCucWb1WpA==",
                            Type = 2,
                            Username = "180321055"
                        },
                        new
                        {
                            LoginId = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Антони",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEPq5YYD1htDnZhWT5WlHxRcMbiMY37Y5RmcAtFgkEJ0bGogbzFC3AB8/E3cIZe0wvQ==",
                            Type = 2,
                            Username = "180321056"
                        },
                        new
                        {
                            LoginId = 58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Щилян",
                            NameLast = "Казаков",
                            Password = "AQAAAAEAACcQAAAAEGG+Zfq55gpntsa0lFidmQo7t5fi1FRAIog/LRe8HIlK4WvZJJho03XBbqC98wyVGw==",
                            Type = 2,
                            Username = "180321057"
                        },
                        new
                        {
                            LoginId = 59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Парушев",
                            Password = "AQAAAAEAACcQAAAAECRRAtJiqN6uym4cBVXaZM0VZFa+P4GGO5w16DyweL4dJvYgI8gqhK1C74b62Dng5A==",
                            Type = 2,
                            Username = "180321058"
                        },
                        new
                        {
                            LoginId = 60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Кратунова",
                            Password = "AQAAAAEAACcQAAAAEKkX0T8xNJqKSXEVG31KnpPAil2MHc7ZEc262Zg6qBgYthte8HgatslZMSNi1OELAQ==",
                            Type = 2,
                            Username = "180321059"
                        },
                        new
                        {
                            LoginId = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Спасимир",
                            NameLast = "Тричков",
                            Password = "AQAAAAEAACcQAAAAEA5oiGaFxWh+TmxFvfsHAyJ4+lJjAfzvEDFYSIQtdsmGCmNFPxi73f9A3RcZ9tbEXA==",
                            Type = 2,
                            Username = "180321060"
                        },
                        new
                        {
                            LoginId = 62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Михаела",
                            NameLast = "Цачева",
                            Password = "AQAAAAEAACcQAAAAEIvlaO5fmOUIT9q63vpugnQCeDrmbYv+Z/RLCE/ePJkDxRPYI4Z4kekSTcQghdOnHw==",
                            Type = 2,
                            Username = "180321061"
                        },
                        new
                        {
                            LoginId = 63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Екрем",
                            NameLast = "Дрянов",
                            Password = "AQAAAAEAACcQAAAAEHPJ3KmR9I7+ubh3brunDgrCSpyqzc964zFAsG6XHCo/2WbFftges0Y75pd4/ovNow==",
                            Type = 2,
                            Username = "180321062"
                        },
                        new
                        {
                            LoginId = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ричард",
                            NameLast = "Христов",
                            Password = "AQAAAAEAACcQAAAAEChUEF/gUSsw21S9sPF3oNuXmAdM5dNFkTC4JwTeg9IOUtTqOi4GlrpJGAYi/XpS+g==",
                            Type = 2,
                            Username = "180321063"
                        },
                        new
                        {
                            LoginId = 65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дейвид",
                            NameLast = "Коуди",
                            Password = "AQAAAAEAACcQAAAAEKC60qMVEKjS3HRDc6LoPpuRHmRAaxnK5IPATa1DFGiKy/KAj6jrh6C3zhwGMN0BkQ==",
                            Type = 2,
                            Username = "180321064"
                        },
                        new
                        {
                            LoginId = 66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дарен",
                            NameLast = "Стоев",
                            Password = "AQAAAAEAACcQAAAAEKXXwtIl/jJ7DCoXISZ5cZudGkjpz0X7gK2JMsI1vqhpsFjjIYiUh/ACdGWno3kP9A==",
                            Type = 2,
                            Username = "180321065"
                        },
                        new
                        {
                            LoginId = 67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йосиф",
                            NameLast = "Йозов",
                            Password = "AQAAAAEAACcQAAAAEFOXXX/kDjDfgzM5rRIObYmKpEXY48r9TcMZgfycYT7F674TUVrDMnr4+WaFRkxm/w==",
                            Type = 2,
                            Username = "180321066"
                        },
                        new
                        {
                            LoginId = 68,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Йордан",
                            NameLast = "Кондаков",
                            Password = "AQAAAAEAACcQAAAAEORmOPmZ+UmTXoF36KhHRcg2ft82Xrpl0AZIX0gVYKbPenPcI45vFn+5JYgqdGMrUA==",
                            Type = 2,
                            Username = "180321067"
                        },
                        new
                        {
                            LoginId = 69,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Бианка",
                            NameLast = "Минева",
                            Password = "AQAAAAEAACcQAAAAENmp66qV3wHfa7kSye1e87m+dhJdMKFPWns3Noi9Qx4pMFpP3r2KLppE5P1NAPYbng==",
                            Type = 2,
                            Username = "180321068"
                        },
                        new
                        {
                            LoginId = 70,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEAgJoEgU4Ekr9ZPlbtXMxH56OI56KjegFKD0182rKcReUf6E6NzuLapHCL8al5Mvhg==",
                            Type = 2,
                            Username = "180321069"
                        },
                        new
                        {
                            LoginId = 71,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Найдев",
                            Password = "AQAAAAEAACcQAAAAEGLwqvnN0nTz1KcEtw6Kw4E01v6XFMnWoxu1rxcEtT43iEkiumimGn4MdJ3ojf2EVg==",
                            Type = 2,
                            Username = "180321070"
                        },
                        new
                        {
                            LoginId = 72,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодор",
                            NameLast = "Пейчев",
                            Password = "AQAAAAEAACcQAAAAEG12rRREN8WCuwg/XEIV5rPBuHguc21f/hLxiD7MU9TqqlaBGFko6Icd4cbXJhTTlg==",
                            Type = 2,
                            Username = "180321071"
                        },
                        new
                        {
                            LoginId = 73,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Петър",
                            NameLast = "Ангелов",
                            Password = "AQAAAAEAACcQAAAAEDLapdWAmjdhdvvJFc0F74rqn5qc/XmyFzhISQxRQubcGi/TBD7noejWAfGQzMB5kQ==",
                            Type = 2,
                            Username = "180321072"
                        },
                        new
                        {
                            LoginId = 74,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Атанас",
                            NameLast = "Янев",
                            Password = "AQAAAAEAACcQAAAAEBo4J7B0pOspuGCzrGwuWUekFHgj0VkrKMgZ7xadXfrRjrsapL6HBKft8JoSHpZrgg==",
                            Type = 2,
                            Username = "180321073"
                        },
                        new
                        {
                            LoginId = 75,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Радостин",
                            NameLast = "Господинов",
                            Password = "AQAAAAEAACcQAAAAEAePNwkTTuCz23jb9F6gb9S0OW5goU2D5d6VlrI90d7DlDzIScYBwd8x+j8FMy3TBw==",
                            Type = 2,
                            Username = "180321074"
                        },
                        new
                        {
                            LoginId = 76,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Теодора",
                            NameLast = "Младенова",
                            Password = "AQAAAAEAACcQAAAAEMbu3i/TPM+BZl9UEMRbkEV1c6nSHRFhYz0RCxNMwrfJplA1Agu8H1jvD1m2YWeSwQ==",
                            Type = 2,
                            Username = "180321075"
                        },
                        new
                        {
                            LoginId = 77,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Величка",
                            NameLast = "Стоянова",
                            Password = "AQAAAAEAACcQAAAAEBl0BUpcELAOY0tsn00V+Gf7MFe/lnAedBpMJobymJqrZfEdBokpxlXh9hbHytCs+g==",
                            Type = 2,
                            Username = "180321076"
                        },
                        new
                        {
                            LoginId = 78,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Лъчезар",
                            NameLast = "Митев",
                            Password = "AQAAAAEAACcQAAAAEKESqR/F1OBCvt6iVbbwAWWKcx06885UAEGaGHPjVSYGPWn4Wf5fhnD5k7dNIccWXg==",
                            Type = 2,
                            Username = "180321077"
                        },
                        new
                        {
                            LoginId = 79,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илияна",
                            NameLast = "Ангелова",
                            Password = "AQAAAAEAACcQAAAAEBte/BVNcsfD/YRCwK+ssH5W5m1q+GbG9iaWgFHt18a/C7V/5F8VEfCFE6YrjeX2ag==",
                            Type = 2,
                            Username = "180321078"
                        },
                        new
                        {
                            LoginId = 80,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Хари",
                            NameLast = "Балабанов",
                            Password = "AQAAAAEAACcQAAAAECUq+KHUj3xu+WL8vHZkQ2L3+cBFfFGKAIRUJunZR9pCLlnddFAHjO2qKTVKi1AtaA==",
                            Type = 2,
                            Username = "180321079"
                        },
                        new
                        {
                            LoginId = 81,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Незиха",
                            NameLast = "Хаджиева",
                            Password = "AQAAAAEAACcQAAAAENWNUMkIiZH9E0OfHco/cj4hCfW0QncBn6e+EaUm/ysYHnRC72PVKPDNZXQ7Tyb/LA==",
                            Type = 2,
                            Username = "180321080"
                        },
                        new
                        {
                            LoginId = 82,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Недялков",
                            Password = "AQAAAAEAACcQAAAAELam2zoDHE3znKzQ/clobKdKGmnk1mpy42AlsK5dHIcMnIUA0FM5UTQ3kGvbnImv2g==",
                            Type = 2,
                            Username = "180321081"
                        },
                        new
                        {
                            LoginId = 83,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Костадин",
                            NameLast = "Запрянов",
                            Password = "AQAAAAEAACcQAAAAEPL8kodyCUtBg22OkhomxMBH2uzHilVQTblPnQeeA/nNPSEIYrkwFKbi/0o7MLww1A==",
                            Type = 2,
                            Username = "180321082"
                        },
                        new
                        {
                            LoginId = 84,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Габриел",
                            NameLast = "Гигов",
                            Password = "AQAAAAEAACcQAAAAEE314/RhMzglI4pF0FVRm5bqQxjqGdKmZDhkSsiUwmxZMlP80rnZh3wk8uDgIIKr0A==",
                            Type = 2,
                            Username = "180321083"
                        },
                        new
                        {
                            LoginId = 85,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Георги",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEHzTQM56Ej/luYHM2J+zYm4hY+Vmbgqi8RAg0nidvG3vW/9B6eLhoeyniJTrBQhlPw==",
                            Type = 2,
                            Username = "180321084"
                        },
                        new
                        {
                            LoginId = 86,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Илиев",
                            Password = "AQAAAAEAACcQAAAAEJ13SySnYdF0Bi0/qKKIVl8lUOzpBbzOcTUH152BUHBqvgLPFnY8oLKW+m6b3qr81g==",
                            Type = 2,
                            Username = "180321086"
                        },
                        new
                        {
                            LoginId = 87,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кристиян",
                            NameLast = "Димов",
                            Password = "AQAAAAEAACcQAAAAEDE5FSLPx55wOXdyHswxHgjifIxTnWEytjfTNm10yW/AXprE2Y3n6+JVd1h1Fd2U3g==",
                            Type = 2,
                            Username = "180321087"
                        },
                        new
                        {
                            LoginId = 88,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Кръстев",
                            Password = "AQAAAAEAACcQAAAAEKTx4a7IHzpNcDXhQR9aT/8JxffCWW7QhlXLIK8TJHKgwVitC9KMExSehfR5yVW8cQ==",
                            Type = 2,
                            Username = "180321088"
                        },
                        new
                        {
                            LoginId = 89,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Тодоров",
                            Password = "AQAAAAEAACcQAAAAEI+yHgLDe1W6w9+0MlJIaeWzDtE0cOSZdWWTwAgW8Cka2FHK+gqC/TahQex7fKJmrg==",
                            Type = 2,
                            Username = "180321089"
                        },
                        new
                        {
                            LoginId = 90,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Виктор",
                            NameLast = "Хаджиев",
                            Password = "AQAAAAEAACcQAAAAEGsfRRbLaXZ+8yiLW6iXBRM+V+9dRPKWX4pNID0BBlrJloTjjgLm53vs0FjSEx0TaA==",
                            Type = 2,
                            Username = "180321090"
                        },
                        new
                        {
                            LoginId = 91,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дилян",
                            NameLast = "Янков",
                            Password = "AQAAAAEAACcQAAAAECNo3hT3NvxoBab1ya6zmpcOrbXGLI6TEw8qEyNN8JT3N1BnGrg4rugc94RVwCwXqw==",
                            Type = 2,
                            Username = "180321091"
                        },
                        new
                        {
                            LoginId = 92,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Алекс",
                            NameLast = "Манолов",
                            Password = "AQAAAAEAACcQAAAAEHBxSGvjs18l0dd0Y6AyIuKU+wavUYSzkCnzRc6zmcmlUndBBy8trp70rX1ICDyZSw==",
                            Type = 2,
                            Username = "180321092"
                        },
                        new
                        {
                            LoginId = 93,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Ивелин",
                            NameLast = "Танев",
                            Password = "AQAAAAEAACcQAAAAENnvquPX6mNUXjRZVFewMSsv/j1RfAR98m2NYdKt15HwuUIZs8m0zXoru6lVUorRSg==",
                            Type = 2,
                            Username = "180321093"
                        },
                        new
                        {
                            LoginId = 94,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валерий",
                            NameLast = "Шулика",
                            Password = "AQAAAAEAACcQAAAAEIIWlnLy+DVR4KAfAn6TOZZaivbNrjSate5lbpttiE6sgcng8TU3vXd2o4ruJPUccQ==",
                            Type = 2,
                            Username = "180321094"
                        },
                        new
                        {
                            LoginId = 95,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Богдан",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEChWNgBZw2Bb6dGxd8LcIkcmZf6qgs/tA+JNanGQvvIxGrMOxhm+njxMJ7OU+D6WCw==",
                            Type = 2,
                            Username = "180321095"
                        },
                        new
                        {
                            LoginId = 96,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Валентин",
                            NameLast = "Ихтияров",
                            Password = "AQAAAAEAACcQAAAAEAmquInC+q2c5Ri+m0P1UEQkx4ISm+9tU5GTks95Qu0KkKTjrdBVhAMLbHEXlJjN7g==",
                            Type = 2,
                            Username = "180321096"
                        },
                        new
                        {
                            LoginId = 97,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Димитър",
                            NameLast = "Костов",
                            Password = "AQAAAAEAACcQAAAAEGPEAApYDW49DB/NOGLCcHDz4YMZEPcAdIx4TtoJCI4F7vLgNuYiTWDP1uAx+zfZkQ==",
                            Type = 2,
                            Username = "180321097"
                        },
                        new
                        {
                            LoginId = 98,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Владислав",
                            NameLast = "Владов",
                            Password = "AQAAAAEAACcQAAAAEG6cKOwOJPp9zgugXhC6DeM3q2zqf3VdFuQTUIdyb+p9T6KqdWLqNL/6qPn3EotA8Q==",
                            Type = 2,
                            Username = "180321098"
                        },
                        new
                        {
                            LoginId = 99,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAEP+YNAukPkL+Oc06TYlIA+DnTPvxv6ZsBJtEPE3Q/ypUod7njYQlnM71XkkzagD8mQ==",
                            Type = 2,
                            Username = "180321099"
                        },
                        new
                        {
                            LoginId = 100,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Артем",
                            NameLast = "Георгиев",
                            Password = "AQAAAAEAACcQAAAAELIIJSL4xPoSv9KUbqa4aj8pYXb4SqAdRHqO4vxQ3BHXgQq5iqGaYiV5oyfU6UIBWw==",
                            Type = 2,
                            Username = "1803261100"
                        },
                        new
                        {
                            LoginId = 101,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Дмитро",
                            NameLast = "Добрев",
                            Password = "AQAAAAEAACcQAAAAEApxTOLwEixQUGR2RaOFM2l1ctLOanH+Mnx91lirGI7BgthAUZ25EGF60lq2nZNmvA==",
                            Type = 2,
                            Username = "1803261101"
                        },
                        new
                        {
                            LoginId = 102,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Кирило",
                            NameLast = "Безниско",
                            Password = "AQAAAAEAACcQAAAAEBlaGnzUanPcRc8FvVRcFCl/NMGJTPCigq1blt1uteusGf5AGsZajqMpYpitrLXxPw==",
                            Type = 2,
                            Username = "1803261102"
                        },
                        new
                        {
                            LoginId = 103,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Биков",
                            Password = "AQAAAAEAACcQAAAAEOZYCI/XcKaNrMGH5wOVVwJ+1jzlZw63Mx4eYABPf24/yQj1V8DJ6C+O9Hy7J8A2pQ==",
                            Type = 2,
                            Username = "1803261104"
                        },
                        new
                        {
                            LoginId = 104,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Илля",
                            NameLast = "Кирилив",
                            Password = "AQAAAAEAACcQAAAAEMt/pHnmQqfyYdjYfZNCoQ2cG1cMATEBpCSYiA9KxF1OoCZKZp/uyoUi9v0RIlSkAA==",
                            Type = 2,
                            Username = "1803261105"
                        },
                        new
                        {
                            LoginId = 105,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Сергий",
                            NameLast = "Сакали",
                            Password = "AQAAAAEAACcQAAAAEEcHO/RjuM5gchhMd198hKGc9qeeGiswVWP+5i85lGyZntWwUbv6SPonWvFVF6MaDA==",
                            Type = 2,
                            Username = "1803261106"
                        },
                        new
                        {
                            LoginId = 106,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Денис",
                            NameLast = "Репев",
                            Password = "AQAAAAEAACcQAAAAEKYNVtcZkvxGnGJm7AeyUm8oxySJw9ia9bhGgLPI6TOK11NNoa3JLrpLg+uvrLQlsQ==",
                            Type = 2,
                            Username = "1803261108"
                        },
                        new
                        {
                            LoginId = 107,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "Николай",
                            NameLast = "Вълчанов",
                            Password = "AQAAAAEAACcQAAAAEMoNMh+GcPjFG/B+yIe2bNufooaTCKa9KGzFBof0hGAEkJUmSaX5A5O8XBlCmHk5GA==",
                            Type = 1,
                            Username = "nikiv"
                        });
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AlwaysAppear")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("relc.Models.Attempt", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Login", "Login")
                        .WithMany("Attempts")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.AttemptAnswer", b =>
                {
                    b.HasOne("relc.Models.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relc.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relc.Models.Question", b =>
                {
                    b.HasOne("relc.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
